### ISSUE TITLE
feat: add hardhat scripts for benchmarking the gas consumption 

### ISSUE THREAD

**Issue by 0xsudo-eth** [chiru-labs/ERC721A#104]
adding scripts to calculate the gas for ERC721A use cases should be beneficial for the project long term roadmap.

with scripts as a source of truth, we would be able to track and check the gas for multiple cases ( mint, transfer..etc) 

if the community agree on using hardhat script as gas estimation i can add those scripts

**Comment by fulldecent** [comment]
Duplicate of #83
