### ISSUE TITLE
One user can burn another user's tokens?

### ISSUE THREAD

**Issue by TravelingTechGuy** [chiru-labs/ERC721A#117]
Hope I got it right - could always be my implementation.
I tried adding a **burn** functionality to my token. I added the following:

```solidity
function burn(uint256 tokenId) public {
    _burn(tokenId);
    emit Burned(msg.sender, tokenId);
}
```

All it does is just pass the token id to `_burn` and emit an event.

I then added this test, which was supposed to fail:

```javascript
it('should not allow user to burn an NFT they don\'t own', async () => {
      await myToken.connect(user1).mint(1, {value: ethers.utils.parseEther(regularPrice)});  //creates a single token with ID 0
      await myToken.connect(user2).burn(0);  //supposed to fail: user 1 owns token 0
});
```

But it does not. I looked into the `_burn` code, and it looks like it does not check ownership before proceeding to transfer the token to `0x0`.

Should this check be enforced by my contract, or is there something missing in the `_burn` function?

**Comment by Austinhs** [comment]
Depending on your logic for burn, While it probably is rare I could see the burn ability existing in some other function. For example... After X amount of time, the contract will burn your previous token and mint you a new 1 or 2. If the contract manages that then it's not an "owner". 

I think the idea with burn was to simply refer to the action of burning but checking for ownership is something that depends on business logic.

But lets see what @Vectorized says -- I think he added this

**Comment by Vectorized** [comment]
Please refer to and use the ERC721ABurnable class. It’s burn function will only allow authorised  users to burn. 

The internal _burn function does not have the authorised check. 

This is to be consistent with OpenZeppelin’s implementation.

**Comment by ahbanavi** [comment]
Also, it was discussed earlier in https://github.com/chiru-labs/ERC721A/pull/61#discussion_r805136352

**Comment by TravelingTechGuy** [comment]
Thanks @Vectorized! I've updated my contract accordingly.

I'd add this to the `README` so people won't just call the internal `_burn`  by mistake.
