### ISSUE TITLE
Setting tokenUri to the ERC721A contract

### ISSUE THREAD

**Issue by amirmfallah** [chiru-labs/ERC721A#122]
Hey, I was having trouble finding the method to setting the token URI while minting tokens. any of you guys has a thought on that?

**Comment by ahbanavi** [comment]
**ERC721A** is a fully compliant implementation of **IERC721**, therefore there's not a method for setting the base URI.  

You should implement it in the driving contract and also override `_baseURI()` method.  

*In the implementing contract:*
```solidity

    string private _baseTokenURI;
    
    function setBaseURI(string calldata baseURI) external onlyOwner {
        _baseTokenURI = baseURI;
    }
    
    function _baseURI() internal view override returns (string memory) {
        return _baseTokenURI;
    }
```

**Comment by ahbanavi** [comment]
**ERC721A** is a fully compliant implementation of **IERC721**, therefore there is not a method for setting the token URI at all.
You should implement it in the driving contract and also override `tokenURI()` method.

**Comment by amirmfallah** [comment]
Thanks. Got it.
