### ISSUE TITLE
feat: `_totalMinted()` function.

### ISSUE THREAD

**Issue by Vectorized** [chiru-labs/ERC721A#124]
With the burn feature, collections will need to check against `_currentIndex` if they want to limit the total number of mints.
Checking against `totalSupply()` can result in new mints being possible if someone burns their token(s).

With upcoming PR #66, users will have to check against `_currentIndex - _startTokenId()` instead.

This can cause some confusion.

I suggest adding an internal `_totalMinted()` function,  
and update the README to encourage checking against `_totalMinted()` instead.

Another option is to put this into #66. 

Let me know your comments. 

If you want to make a PR for this issue, please feel free to do so. Drop a comment below too. 

Otherwise, I will probably wait a few / several days after #66 is merged before starting a PR for this (if this feature is not in a PR or merged by then). 

@cygaar @ahbanavi

**Comment by ahbanavi** [comment]
Yes, `_totalMinted()` method would be convenient for this.  
IMO, we better wait for #66 to be merged first. 
Putting it in #66 also do the job I think, and it would be faster, but it's out of context of that PR.

**Comment by cygaar** [comment]
I think I'd prefer it in #66 just so no one accidentally copies this code and runs into an issue checking against `_currentIndex`. Thoughts on that approach? I'd like to make that change "atomic"

**Comment by ahbanavi** [comment]
I agree to add in #66. True, being “atomic” is important on this matter.
