### ISSUE TITLE
Unable to stake using ERC-721A?

### ISSUE THREAD

**Issue by rafaelbate** [chiru-labs/ERC721A#130]
Hello, first of all let me congratulate the Chiru Labs team for their innovative change which led to the current 721A contract, that was really well thought!

So I am developing a project and wanted to integrate 721A with it. As a part of the roadmap, we want to enable users to stake their tokens. To do this, we are doing the following:

- Using a "stake.sol" contract to handle all the staking. In this contract, we call a function "stakingTokens", that will check all the conditions prior to staking (if the user is the owner of the token, if the token isn't already staked, etc…). After checking all the conditions, we call the "transferFrom" function of the ERC-721A contract and send the usual parameters "msg.sender", "address(this)", "_tokenIds". 
- The issue starts now. In line [409](https://github.com/chiru-labs/ERC721A/blob/46fac01652c9e4a9afd02e06ab7d89c0e14910b3/contracts/ERC721A.sol#L409) when the "_transfer" function of the 721A checks if "isApprovedOrOwner". The problem is, the "msg.sender" address will belong to the contract that is calling "_transfer" (which will be the address of "stake.sol"), and not to the actual owner. This will raise an error, making it unable to stake the tokens. 

Are we missing something? Our staking used to work when we were using ERC-721, but stopped working when we integrated ERC-721A.

![image](https://user-images.githubusercontent.com/37276898/155317488-a3232f1c-fce5-4896-91ad-ca51e360fa7b.png)

**Comment by Vectorized** [comment]
Did you add an additional button on your dApp to let the user approve the staking contract to transfer on their behalf? 

This is so that `isApprovedForAll` returns true.

**Comment by santiq** [comment]
@Vectorized 

Could one overwrite the isApprovedForAll to return `true` for a staking contract, that way users don't have to approve it and thus save a transaction?

**Comment by Vectorized** [comment]
@santiq 

> Could one overwrite the `isApprovedForAll` to return `true` for a staking contract, that way users don't have to approve it and thus save a transaction?

Yes. But it is **_dangerous_** practice. **_Not recommended._**

Your users also have to trust that whoever you approve won't rug them.

Some savvy users will consider this a red flag.

```solidity
contract NFT is ERC721A, Ownable {

    mapping(uint256 => bool) internal _globalOperatorApprovals;

    function setGlobalContractApproval(address minter, bool approved) external onlyOwner {
        _globalOperatorApprovals[minter] = approved;
    }

    function isApprovedForAll(address owner, address operator) public view override returns (bool) {
        return (_globalOperatorApprovals[operator] || ERC721A.isApprovedForAll(owner, operator));
    }
}
```

**Comment by rafaelbate** [comment]
Thanks for your proposals.

Summing up, we ended up doing the following:

- Commented lines [409](https://github.com/chiru-labs/ERC721A/blob/46fac01652c9e4a9afd02e06ab7d89c0e14910b3/contracts/ERC721A.sol#L409) and [413](https://github.com/chiru-labs/ERC721A/blob/46fac01652c9e4a9afd02e06ab7d89c0e14910b3/contracts/ERC721A.sol#L413) of ERC-721A;
- We overrode transferFrom() in our main contract for it to check if the "msg.sender" is not the contract, and, if it is not the contract, we verify if the user is the holder of the token;
- Once we verify that the user is the owner of the token, we call the _transfer function of ERC-721A.

This is safe because once the contract is deployed, the owner is not able in any shape or form to transfer tokens from a user wallet to the contract. Only the contract itself is able to do it. 

This way, users don't have to pay any extra gas fees to approve for something. When a user accepts to stake, it is implied that they "approve" the staking, hence we end up saving gas fees for the user. 

Everything is running smoothly now. 

If you find this is a suitable solution, you may close this issue.

**Comment by codesport** [comment]
> * Using a "stake.sol" contract to handle all the staking. In this contract, we call a function "stakingTokens", that will check all the conditions prior to staking (if the user is the owner of the token, if the token isn't already staked, etc…). After checking all the conditions, we call the "transferFrom" function of the ERC-721A contract and send the usual parameters "msg.sender", "address(this)", "_tokenIds".

@rafaelbate would you be able to provide a link to a reference contract for `Stake.sol` for either ERC-721 or ERC-721a so the community can learn how it should be implemented?

**Comment by rafaelbate** [comment]
> > * Using a "stake.sol" contract to handle all the staking. In this contract, we call a function "stakingTokens", that will check all the conditions prior to staking (if the user is the owner of the token, if the token isn't already staked, etc…). After checking all the conditions, we call the "transferFrom" function of the ERC-721A contract and send the usual parameters "msg.sender", "address(this)", "_tokenIds".
> 
> @rafaelbate by any chance, would you be able to provide a link to a reference contract for `Stake.sol` for either ERC-721 or ERC-721A? I'm sure others have the same question. I'm curious with how to this, And it would definitely help the community learn how it should be implemented.
> 
> If I find something I will post it here so others can benefit. Google is everybody's friend!

I will post it in a near future, Right now I am not able to do it due to NDA.
