### ISSUE TITLE
Documentation for Aux / Aux Use Case

### ISSUE THREAD

**Issue by kyokosdream** [chiru-labs/ERC721A#135]
First of all, thank you @chiru-labs for your contribution to the open-source community with ERC721A. I really enjoyed reading the following article and picking through the contract code. 

[https://www.azuki.com/erc721a](https://www.azuki.com/erc721a)

I've noticed you've made some additions since I implemented ERC721A in my contract, but there is no documentation or official changelog for these changes other than just examining the commits. 

I'm wondering why the inclusion of the `burn` function in the base ERC721A contract. Would it not have been more ideal to create a separate contract that implements burning functionality than including it in the base contract? None of the projects I've been involved with have desired this functionality and I'm wondering if the extra logic it requires increases gas costs at all. 

I'm also wondering if the purpose of the aux field can be explained better. I see that the comments indicate it is used to indicate how many "whitelist slots" have been used. 

In my team's contract we use an off-chain API we created for generating a Merkle root hash (that is then set on a contract) and for generating Merkle proofs which are submitted to our `whitelistMint` function. Once a whitelisted address calls the function, they are immediately invalidated by setting `whitelistClaimed[_msgSender()] = true;`. The problem with this is that if we allow whitelisted users to mint a total of let's say 3 tokens, but they only choose to mint 1, they are invalidated from the whitelist after their first call to the function and cannot mint any more. 

```javascript
uint256 private maxWhitelistMints = 3;
```

```javascript
  // @notice this is the mint function, mint Fees in ERC20,
  //  requires amount * mintPrice to be sent by caller
  //  nonReentrant() function. More comments within code.
  // @param uint amount - number of tokens minted
  function whitelistMint(bytes32[] calldata merkleProof, uint256 amount) external payable nonReentrant() {
    // @notice using Checks-Effects-Interactions
    require(mintingActive, "Minting not enabled");
    require(whitelistActive, "Whitelist not required, use publicMint()");
    require(_msgValue() == mintPrice * amount, "Wrong amount of Native Token");
    require(_totalSupply() + amount <= mintSize, "Can not mint that many");
    require(amount <= maxWhitelistMints, "Exceeds maximum whitelist mints");
    require(
          MerkleProof.verify(
              merkleProof,
              whitelistMerkleRoot,
              keccak256(abi.encodePacked(_msgSender()))
          ),
          "Address not whitelisted"
    );
    require(!whitelistClaimed[_msgSender()], "You have already claimed your tokens");
    _safeMint(_msgSender(), amount);
    whitelistClaimed[_msgSender()] = true; 
  }
```

Personally, I'm fine with the way this works, since I think whitelisted addresses should only have one chance to mint the maximum number of tokens they are allowed to mint. However, ideally, we would keep track of how many they have minted respective to their maximum allowance, and allow them to call the function again if they have not yet exceeded this limit. 

Is this the use case intention for the aux owner data with respect to whitelisting?

**Comment by Vectorized** [comment]
@kyokosdream 
Yes, that is the intention of aux.

In your example, you have used a separate mapping is used to record whether users have claimed their whitelist mints. 
This costs around about 22k more gas, as the code will need to read + write a separate 256 bit word in storage.  

This is how you can do it with aux:

```solidity

  // @notice this is the mint function, mint Fees in ERC20,
  //  requires amount * mintPrice to be sent by caller
  //  nonReentrant() function. More comments within code.
  // @param uint amount - number of tokens minted
  function whitelistMint(bytes32[] calldata merkleProof, uint256 amount) external payable nonReentrant() {
    // @notice using Checks-Effects-Interactions
    require(mintingActive, "Minting not enabled");
    require(whitelistActive, "Whitelist not required, use publicMint()");
    require(_msgValue() == mintPrice * amount, "Wrong amount of Native Token");
    require(_totalSupply() + amount <= mintSize, "Can not mint that many");
    require(amount <= maxWhitelistMints, "Exceeds maximum whitelist mints");
    require(
          MerkleProof.verify(
              merkleProof,
              whitelistMerkleRoot,
              keccak256(abi.encodePacked(_msgSender()))
          ),
          "Address not whitelisted"
    );
    require(_getAux(_msgSender()) == 0, "You have already claimed your tokens");
    _safeMint(_msgSender(), amount);
    _setAux(_msgSender(), 1); 
  }
```

The compiler will pack the whitelist minting data into the same 256 bit word that is used for storing user balances, mint counts, and burn counts. This avoids the overhead of an extra storage read and write.

Whitelist minting is one of the most common use case.

We want to give developers room to explore what they want to do with aux. 

**On burn:**

As for burn, it can be a useful if you want to have future contracts that can burn NFTs to get new mints. 

We have profiled the code to make sure that the gas costs still remain roughly the same, with or without burn.
If you don't use it, the compiler can remove the unused code away to reduce deployment gas costs. 

Due to burn logic being heavily intertwined with many parts of the main logic, it is not feasible to separate the bulk of the burn. In OpenZeppelin, a lot of the burn logic is contained in their ERC721 file and ERC721Enumerable file.

**Comment by kyokosdream** [comment]
Thanks for your quick reply @Vectorized! I understand why burn is included in the base contract and glad to know that it has roughly the same gas cost. 

I see at the end of the modified whitelist function you helpfully edited for me:

```javascript
_setAux(_msgSender(), 1);
```

Wouldn't I actually want to first query the number of whitelist slots and then decrement by the `amount` parameter in the mint function?

```javascript
_setAux(_msgSender(), _getAux(_msgSender() - amount));
```

Is this correct? Thanks for helping me understand the Solidity compiler better

**Comment by Vectorized** [comment]
@kyokosdream 

```solidity
  // @notice this is the mint function, mint Fees in ERC20,
  //  requires amount * mintPrice to be sent by caller
  //  nonReentrant() function. More comments within code.
  // @param uint amount - number of tokens minted
  function whitelistMint(uint256 numReserved, bytes32[] calldata merkleProof, uint256 amount) external payable nonReentrant() {
    // @notice using Checks-Effects-Interactions
    require(mintingActive, "Minting not enabled");
    require(whitelistActive, "Whitelist not required, use publicMint()");
    require(_msgValue() == mintPrice * amount, "Wrong amount of Native Token");
    require(_totalSupply() + amount <= mintSize, "Can not mint that many");
    require(amount <= maxWhitelistMints, "Exceeds maximum whitelist mints");
    require(
          MerkleProof.verify(
              merkleProof,
              whitelistMerkleRoot,
              keccak256(abi.encodePacked(_msgSender(), numReserved))
          ),
          "Address not whitelisted"
    );
    uint256 numWhitelistMinted = _getAux(_msgSender()) + amount;
    require(numWhitelistMinted <= numReserved, "Not enough whitelist slots.");
    _safeMint(_msgSender(), amount);
    _setAux(_msgSender(), numWhitelistMinted); 
  }
```

Consider incrementing the number of whitelist slots used instead.

**Comment by kyokosdream** [comment]
Thanks @Vectorized really appreciate your help and very happy to see ERC721A being implemented in Hashlips as well. Look forward to further discussions with you. For now I'm going to close this issue so others can be addressed.

**Comment by kyokosdream** [comment]
Sorry for closing the issue pre-emptively but I had a final question which is that is my `maxWhitelistMints` variable still required here? 

It seems to me at least with a quick glance that `numReserved` can replace it? Also could you explain why `numReserved` is included as a function parameter in the updated code instead of outside the function as a state variable?

I'm happy to move the discussion to Twitter if you want issues on this repo to only be directly related to changes to ERC721A and not our implementation.

**Comment by Vectorized** [comment]
@kyokosdream You can remove it.

**Comment by kyokosdream** [comment]
Thanks.

Our [CandyCreatorV1A](https://github.com/Candy-Labs/CandyContracts/blob/main/contracts/CandyCreatorV1A.sol) whitelistMint implementation updated to use the latest `_getAux` and `_setAux` functions included in the latest ERC721A code. Will provide additional tests for our `whitelistMint` function in an upcoming release. 

Closing the issue.

**Comment by 0xS0l** [comment]
@kyokosdream @Vectorized instead of using `aux`, can we use `_numberMinted` method, like this
```
require(amount + _numberMinted(msg.sender) <= maxWhitelistMints, "...");
```
?

TIL about `aux`, it's really cool though :+1:
