### ISSUE TITLE
OpenSea not showing all Tokens

### ISSUE THREAD

**Issue by duro721** [chiru-labs/ERC721A#136]
Hey there,

Not even sure if this is an issue of the ERC721A, but once i moved from ERC721enumerable to ERC721A after deploying on Rinkeby and minting a few tokens. I don't see all tokens listed. I noticed that i only see as many tokens as owners. Even when i look in the profile collected of an address that minted 3 i only see 1 token.

Is there something extra we have to do with ERC721A and OpenSea to have it show all tokens?

thanks in advance.

**Comment by Vectorized** [comment]
This is a known issue of OpenSea. They probably missed out on listening to some `Transfer` events. 

If you directly go the the OpenSea URI of the missing token, you should see that the token is there.
`https://testnets.opensea.io/assets/<contract_address>/<token_id>`

**Comment by duro721** [comment]
Ah sweet, thanks for the quick response. Is this something only happen on testnet OpenSea? or do we also see this with launched projects on Mainnet?

I've been looking at a few projects that launched like Tasty Bones, but its hard to figure out with so many tokens minted :)

**Comment by Vectorized** [comment]
I've encountered it on Mainnet OpenSea sometimes. Don't worry too much about it.

**Comment by jamessayer98** [comment]
Is there any limit of tokens that we can mint per transaction with ERC-721a?

**Comment by jamessayer98** [comment]
We are going to launch our 10k items and wanted to make sure if it can be minted within a single transaction along with ERC-721a. Thanks

**Comment by Vectorized** [comment]
@jamessayer98 This should be in a new issue, but anyways... 

Yes. Each token minted will emit a `Transfer` event via a `LOG4` opcode (which costs 1875 gas). 

Given the current limit of 30000000 gas per transaction on Ethereum, this means you can at most mint approx. 16000 in a single transaction. 

Batch sizes that are too large can have a detrimental impact on transfer gas fees, if the tokens are not transferred in increasing token ID order. 

You may want to mint large batches into small chunks, or impose a reasonable limit on the number of mints per transaction (e.g. 10). See #145.

**Comment by jamessayer98** [comment]
Thank you for your detailed explanation.

Would you suggest the way that we can spend the lowest gas fee for 10k minting?
- We can set the bactch size 10k and mint 10k items in a single transaction(following your document, i believe it is the best way to optimize the gas)
- Bacth 10k NFTs with small chunks as you suggested(e.g. 4~10) and mint 4~10 items per transaction

I see most of the projects using ERC-721a including you Azuki followed the 2nd option and they mostly set the batchy size 3~6. I realized you minted 199 items with dev mint and 4~5 items with auction mint. Is there any reason you guys set the batch size small? I'm sorry if I am not correct.

**Comment by Vectorized** [comment]
The smaller batch size for public serves two purposes: 
- Encourage a more even distribution of tokens.
- Capping the transfer gas costs on batch minted tokens if they are not transferred in increasing token ID order.

**Comment by Wakdman** [comment]
> Vectorized

Hello Vectorized thank you so much for all your input 
As i'm Newbie i wanted to make sure i understand your advise 
You say that we could mint approximately 16000 NFTS in one single transaction. 

1)Does that mean that you pay a transaction fee for every NFTs , or one transaction fee for all 16K? 
Because i see you advise to mint per batch of 8 .

2)What is the difference between dev mint and auction mint ?

Thank you

**Comment by Vectorized** [comment]
@Wakdman 1 very large tx fee for 16k.

Dev mint is just the dev minting to their own wallet. Auction mint is for public.
