### ISSUE TITLE
Suggestion: add contract version

### ISSUE THREAD

**Issue by ahbanavi** [chiru-labs/ERC721A#138]
It would be a good idea to add the release version on top of the [contracts/ERC721A.sol](https://github.com/chiru-labs/ERC721A/blob/main/contracts/ERC721A.sol) file and update it when a new version releases.  
Some devs or savvy people would like to know what version of `ERC721A` the implemented contract uses. 

```solidity
// SPDX-License-Identifier: MIT
// ERC721A v2.2.0
// Creator: Chiru Labs
.
.
.
```

**Comment by ahbanavi** [comment]
@cygaar please consider this for next version release, I'm waiting to hear your thoughts before closing this issue.

**Comment by Vectorized** [comment]
Probably will look into some workflow that can run a script to do this some time after next version. 

I suggest either a shell script (e.g. `scripts/replace-contract-versions.sh`), or js snippet (e.g. `scripts/replace-contract-versions.js`) that can read from `package.json` and update the files in `contracts`.

For an example, see https://github.com/Vectorized/ERC721A-Upgradeable/

**Comment by ahbanavi** [comment]
> It would be nice to have this version stamp as well for contract review.
@Austinhs Exactly, that was my main intention for raising this issue.

**Comment by ahbanavi** [comment]
> I suggest either a shell script (e.g. `scripts/replace-contract-versions.sh`), or js snippet (e.g. `scripts/replace-contract-versions.js`) that can read from `package.json` and update the files in `contracts`.

I'm working on a script to change the `package.json` version and comments simultaneously, so maintainers could just update all files on bump version PR, like #179 #39 …

I'm using this issue to discuss the implementation of this.

you can see the script here at [scripts/release/update-version.js](https://github.com/ahbanavi/ERC721A/blob/ci/contract-version/scripts/release/update-version.js)
the usage is as simple as: 
```bash
./scripts/release/update-version.js 3.2.0
```
or even use it as:
```bash
npm run update-version 3.2.0
```

And then, the `package.json` version and all other files will update.
The header of all `.sol` files will look like this:
```
// SPDX-License-Identifier: MIT
// ERC721A Contracts v3.2.0
// Creator: Chiru Labs
```

We can also ignore the mocks, but adding a version comment will not do any harm, IMO.

I would like to mention that this script will update all files, apart from whether they have been modified since the last tag version.
We can update just modified files using git, like the OZ implementation of this script. [See here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/scripts/release/update-comment.js)

> Probably will look into some workflow  

I don't like changing source code and committing it to the main branch in the workflow; problems may occur. Using this script manually is okay, IMO.

I'm waiting to hear your thoughts on this implementation before opening a PR.
@cygaar @Vectorized

**Comment by Vectorized** [comment]
@ahbanavi Make a PR. 

My 2 cents:

While OZ only updates the version in the updated files, I think having the same version number across all files has the advantage that it is easy to know two files are meant for each other. For example #214 was caused by the files being from different versions. 

Also, it is simpler to just replace the version number in all the .sol files.
