### ISSUE TITLE
Question: how to get n random number/simulate randomicity in ERC721A?

### ISSUE THREAD

**Issue by TravelingTechGuy** [chiru-labs/ERC721A#140]
Our NFT can mint 1 of 6 different types. In a previous version, where ERC721 was used, and we only minted 1 at a time, I simulated a random number by using block time , block height, current token ID and a bunch of other numbers I had lying around, and took a mod 6.

But now, since minting n tokens is an atomic operation, all those numbers are essentially constant for the duration of the operation, meaning the user will mint n of the same token. Adding trivial behavior like rotation still allows the user to calculate which token they'd get.

I attempted to use Chainlink VRF V2 to receive random numbers. This made the operation extremely lengthy, expensive (both gas and Link), and worse unpredictable (nearly 7 minutes on Rinkeby) and dependent on a callback function from the Chainlink Oracle.

How can I allow a user who's minting n token to get n different ones? Is anyone out there relying on random outcome using ERC721A?
Ideas are welcome.

**Comment by Vectorized** [comment]
This is off topic, but I suggest you to consider a one-time reveal or in large batches. 

And do make sure the choice (1-6) is calculated in a pure/view function from the hash of the randomness with the token id. Don’t write the choice onto the chain.
