### ISSUE TITLE
Aux uint64 packing

### ISSUE THREAD

**Issue by kyokosdream** [chiru-labs/ERC721A#144]
Our team is looking to also store two booleans in addition to the number of whitelist mint slots remaining. 

I know Solidity bool takes 1 byte,  but can be represented with a single bit in theory. Should I use bitwise operations to encode these in the last two bits of the uint64 or the last two bytes? 

Or would a better path to be to just remove the uint64 aux and replace it with multiple smaller memory variables that fit  the same slot? 

Our whitelist slots will never be that large of a number, to be honest, likely a single digit integer. In this case, according to strategy in the last paragraph, would it be better to just store a  uint8 (1 byte) and 2 bools (2 bytes) and they will be packed into the Ownership struct the same way as currently exists in the repo?

Thanks for your help!

**Comment by Vectorized** [comment]
Use the first two bits for the booleans, and the rest for the whitelist mint count.

The reason why only have a single uint64 our library is to give the most flexibility for users. We don’t know how many bits and what kind of variables users want to store.

**Comment by kyokosdream** [comment]
Unsure of why when calling the `vote()` function a second time the "Vote Status" is still zero. Something wrong with my masking?

```javascript
function vote(bool approveWithdrawal) external {

    // INITIAL 
    // [0000000000000000]

    // If user has not minted any and has not voted 
    // result is 
    // [(00)00000000000000]
    // AND 
    // [1100000000000000]
    // =
    // [0000000000000000] = 0x0000 HASN'T VOTED, NO VOTE
    // FIRST BYTE = [0000]

    // If user has minted 69 tokens already but hasn't voted 
    // result is 
    // [(00)00000001000101]
    // AND
    // [1100000000000000]
    // =
    // [0000000000000000] = 0x0000 HASN'T VOTED, NO VOTE
    // FIRST BYTE = [0000]

    // If user has minted 69 tokens alreqady but has voted no 
    // result is 
    // [(10)00000001000101]
    // AND
    // [1100000000000000] 
    // = 
    // [1000000000000000] = 0x8000 = HAS VOTED, VOTED NO
    // FIRST BYTE = [1000]

    // If user has minted 69 tokens already but has voted yes 
    // result is 
    // [1100000001000101]
    // AND
    // [1100000000000000]
    // = 
    // [1100000000000000] = 0xC000 = HAS VOTED, VOTED YES 
    // FIRST BYTE = [1100]

    // Require the sender to own tokens 
    require( balanceOf(_msgSender()) > 0, "User does not own any tokens");

    // Get the usedWhitelist slots 
    // If we use 1 byte to store the voteData, the other 7 can represent the usedWhitelistSlots as a uint56
    // Discard the first 8 bits (1 byte) which encodes the voteData
    uint56 usedSlots = uint56(_getAux(_msgSender()) << 8);
    console.log("Used whitelist slots");
    console.log(usedSlots);

    console.log("Current Aux");
    console.log(_getAux(_msgSender()));

    // Get the vote data 
    // mask is cast to uint64 for fixed-length alignment AND operation
    uint64 voteData = _getAux(_msgSender()) & uint64(0xC);

    console.log("Vote Status");
    console.log(voteData);
    
    // Catch cases
    if (voteData == 192) {
      console.log("User has voted YES");
    }
    if (voteData == 128) {
      console.log("User has voted NO");
    }

    // Revert execution if vote has already been recorded 
    //require(voteData == 0, "Vote already recorded");

    // This byte (voting data) will be concatenated with the other 7 bytes / 56 bits that store the usedWhitelist slots 
    bytes1 newVote;

    if (approveWithdrawal == true) {
      newVote = bytes1(0xc0); // 11(00) = 192 = Vote Yes
      console.log("User is voting YES");
    } else {
      newVote = bytes1(0x80); // 10(00) = 128 = Vote No
      console.log("User is voting NO");
    }

    // Cast the previously retrieved usedSlots (56 bits) to bytes7 
    bytes7 usedSlotsBytes = bytes7(usedSlots);
    bytes memory result = bytes.concat(newVote, usedSlotsBytes);

    // Cast to uint64 type required by ERC721A
    uint64 newAux = uint64(bytes8(result));

    // Set the resulting uint64 as the ERC721A aux variable
    _setAux(_msgSender(), newAux);

  }
```

**Comment by kyokosdream** [comment]
I'm still working on this and rather new to Solidity, I'll leave by previous naiive attempt up until I fix the other function but for anyone following my latest iteration:

```javascript
function vote(bool approveWithdrawal) external {

    // INITIAL: 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000 0000
    uint64 aux = _getAux(_msgSender()); 

    // Check if first bit of 64 bit aux is set 
    bool hasVoted = (aux & (1 << 63)) > 0;

    // Check if second bit of 64 bit aux is set
    bool votedYes = (aux & (1 << 62)) > 0;

    console.log("Bit 1 Set");
    console.log(hasVoted);  

    console.log("Bit 2 Set");
    console.log(votedYes);

    require(!hasVoted, "User has already cast their vote");

  }
```

**Comment by kyokosdream** [comment]
```javascript
uint64 aux = _getAux(_msgSender()); 

// The uint56 value of the last 56 bits of the ERC721A uint64 aux variable
uint56 numWhitelistMinted = uint56((aux) % 2 ** 56);
```

**Comment by kyokosdream** [comment]
We've released a rough draft for a community governed ERC721(A) contract on our Github under the [voting](https://github.com/Candy-Labs/CandyContracts/blob/voting/README.md) branch.

It demonstrates an example of allowing token holders to vote on allowing the contract owner to release funds. It does so by preventing token transfer and minting during the voting period. It uses the first 8-bits of the ERC721A `uint64 aux` variable to track the last proposal voted on by the user (for preventing double-voting) and uses the last 56-bits for the whitelist mint slots. 

The first 8 bits allow encoding up to 0-255 proposals but we only allow a maximum of 100 in the current implementation. We use the decimal value 101 as a special case to track whether the refund has been claimed. 

README
https://github.com/Candy-Labs/CandyContracts/blob/voting/README.md

Let us know how we can best credit this project and it's authors/maintainers and provide an example for users to perform bit packing with the new aux variable.

**Comment by Vectorized** [comment]
Looks good. 
Just leave a link this repo in your README or website. Thank you for the great support.

**Comment by kyokosdream** [comment]
Link to this repo added to the top of the aforementioned README file. Closing the issue so others can be addressed.
