### ISSUE TITLE
Make setApprovalForAll virtual

### ISSUE THREAD

**Issue by KirienzoEth** [chiru-labs/ERC721A#148]
Hello!

Would it be possible to make `setApprovalForAll` virtual? That's the case in OpenZeppelin's ERC721 implementation. Or are there any reasons why `isApprovedForAll` is virtual, but not `setApprovalForAll`?

It would be useful because of the various gas optimization strategies involving approving marketplace proxys by default (among others), which require you to override `isApprovedForAll` to add some custom logic.

IMHO, some custom logic is also necessary in `setApprovalForAll` so users can revoke those default approvals the same way they'd revoke any address's approvals, thus why I would like to be able to override that method.

**Comment by Vectorized** [comment]
Sounds good. You can make a PR. 

@cygaar what do you think?

**Comment by KirienzoEth** [comment]
Done here: #149

**Comment by cygaar** [comment]
PR merged

**Comment by KirienzoEth** [comment]
Thank you 🙏
