### ISSUE TITLE
Too many tokens!!!

### ISSUE THREAD

**Issue by fulldecent** [chiru-labs/ERC721A#159]
Each owner is limited to owning 2^64 token as per `uint64 balance` in `AddressData`.

However, the `_mint`, `_safeMint`, `_beforeTokenTransfers`, `_afterTokenTransfers` functions all use the uint256 type which is too wide.

Those functions are all internal so perhaps narrowing the type is appropriate.

**Comment by mustafa519** [comment]
I tried to use `getAux`, `setAux` helpers for whitelist counter. I haven't tested the gas difference yet, but I use unsigned 256 bit integer for the most purposes. Like maxSupply, mintPrice, maxPerWhitelist etc. So I had to transform all the variables from 64 to 256 again in the setter mint function to sum or calculate the things.

And, I heard, the compiler creates uint256 by default and for this implementation it needs transforming from 256 to 64 which causes more gas costs on those purposes above. Specially in runtime calculations instead first deployment.

PS: I am very new in Solidity.

Thanks for the efforts to make ERC721 better.

**Comment by Vectorized** [comment]
I think it’s ok to just leave it as it is.

Otherwise users have to cast the quantity to uint64 (a little inconvenient), and the compiler may emit an extra opcode for the casting.

In practice, the function will run out of gas way before the _quantity can even hit the uint64 max.

**Comment by TravelingTechGuy** [comment]
Does anyone have a code sample using `setAux` and `getAux`? Would like to learn how are they used to whitelist.

**Comment by Vectorized** [comment]
@TravelingTechGuy see #135
