### ISSUE TITLE
Batch Size Inquiry

### ISSUE THREAD

**Issue by rosman83** [chiru-labs/ERC721A#16]
The concept of minting in defined batches is interesting - but that brings the question - is their an optimal batch size where different gas savings are seen and say a batch size was initiated at 1. Wouldn't that defeat the purpose of the optimization - and if so should we be adding a check to prevent a batch size of one?

**Comment by cygaar** [comment]
We still need to give the option to mint 1 token - unless I'm misunderstanding you?

**Comment by cygaar** [comment]
Closing this for now, feel free to re-open if you have any other questions
