### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by fadikc** [chiru-labs/ERC721A#163]
I keep getting the following error when using remix to create my cotract:

            DeclarationError: Undeclared identifier.
--> contracts/DAL.sol:95:31:
|
95 | ownerIds[index] = tokenOfOwnerByIndex(_owner, index);
                           | ^^^^^^^^^^^^^^^^^^^

Although it is identified in both IERC721.sol and IERC721Enumerable.sol

Any ideas?

Thanks

**Comment by Vectorized** [comment]
We have removed tokenOfOwnerByIndex. 

See #107
