### ISSUE TITLE
tokenURI returns empty string everytime

### ISSUE THREAD

**Issue by Anarr** [chiru-labs/ERC721A#187]
```
//Contract based on [https://docs.openzeppelin.com/contracts/3.x/erc721](https://docs.openzeppelin.com/contracts/3.x/erc721)
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "erc721a/contracts/ERC721A.sol";

contract MyNFT is ERC721A {

    constructor() ERC721A("MyNFT", "MNFT") {}

  function mint(uint256 quantity, bytes memory tokenUri) external payable {
    // _safeMint's second argument now takes in a quantity, not a tokenId.
    _safeMint(msg.sender, quantity, tokenUri);
  }
}

```

Even the transaction was successful after calling `mint()` method, but the tokenURI() returns empty string every time. When I import the nft my wallet it does not preview the image.

The nft meta data is: https://gateway.pinata.cloud/ipfs/QmYcmYEkkr6fPCQUV2Vss8cFYYQm4CQiYCZudahNHnqp7G

**Comment by Vectorized** [comment]
The bytes parameter in `_safeMint` function of ERC721A isn't for passing the token URI. 
It is for passing to the minted to's address, if the address is a contract.

Say if your baseURI is `https://ikzttp.mypinata.cloud/ipfs/QmQFkLSQysj94s5GvTHPyzTxrawwtjgiiYS2TBLgrvw8CW/`, such that the json URI of tokenID 123 is `https://ikzttp.mypinata.cloud/ipfs/QmQFkLSQysj94s5GvTHPyzTxrawwtjgiiYS2TBLgrvw8CW/123`, this is how you'd do it.

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "erc721a/contracts/ERC721A.sol";

contract MyNFT is ERC721A {

    constructor() ERC721A("MyNFT", "MNFT") {}
    
    function _baseURI() internal view override returns (string memory) {
        return 'https://ikzttp.mypinata.cloud/ipfs/QmQFkLSQysj94s5GvTHPyzTxrawwtjgiiYS2TBLgrvw8CW/';
    }

    function mint(uint256 quantity) external payable {
        // _safeMint's second argument now takes in a quantity, not a tokenId.
        _safeMint(msg.sender, quantity);
    }
}
```

**Comment by Anarr** [comment]
@Vectorized thank you, maybe I missed something from doc. It works!

**Comment by honorableCon** [comment]
Can we set custom URI like _setTokenURI from "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
