### ISSUE TITLE
How to import ERC721A to remix?

### ISSUE THREAD

**Issue by justChargin** [chiru-labs/ERC721A#190]
![image](https://user-images.githubusercontent.com/46795644/159116401-c832ce40-bfe3-4ff2-8654-0d36eca1ceca.png)

This not working, how can i import it?

**Also, if i mint one nft and transfer it another person on my opensea account it can be a problem for another mint?**

**Comment by Vectorized** [comment]
Just copy the import line in the example on the README. 😉

**Comment by justChargin** [comment]
> Just copy the import line in the example on the README. 😉
> 
> `import "erc721a/contracts/ERC721A.sol";`

Is there an example simple NFT contract using ERC721A? Can i use ERC721A with hashlips?

**Comment by Vectorized** [comment]
https://github.com/hashlips-lab/nft-erc721-collection This is using ERC721A.
