### ISSUE TITLE
What means batchsize?

### ISSUE THREAD

**Issue by justChargin** [chiru-labs/ERC721A#191]
![image](https://user-images.githubusercontent.com/46795644/159117367-b033aecd-2310-42e2-8f0e-0daaf88a71b0.png)

what means maxbatchsize_ and collectionsize_?

**Comment by Vectorized** [comment]
`maxbatchsize_` is the max quantity that can be minted in a single batch.

`collectionsize_` is the maximum number of NFTs that can ever be minted in the collection

**Comment by justChargin** [comment]
> `maxbatchsize_` is the max quantity that can be minted in a single batch.
> 
> `collectionsize_` is the maximum number of NFTs that can ever be minted in the collection

You mean maxbatchsize_ is working like **maxMintAmountPerTransaction**?
and collectionsize_ is working like **maxSupply**, right?

**Comment by justChargin** [comment]
![image](https://user-images.githubusercontent.com/46795644/159118073-485d425a-544a-4b3d-aa5c-8e57a8ecf47d.png)

Why am i getting this error?

**Comment by Vectorized** [comment]
> You mean maxbatchsize_ is working like maxMintAmountPerTransaction?
and collectionsize_ is working like maxSupply, right?

Yes.

> Why am i getting this error?

We have changed ERC721A a lot since the original Azuki release. Now, it only accepts 2 arguments in the constructor.
