### ISSUE TITLE
What is the best way to transfer ownership?

### ISSUE THREAD

**Issue by justChargin** [chiru-labs/ERC721A#193]
Is it okay to use transfer ownership method from contract? I have a customer who wants to sell nft's he wants to be owner of the contract. What are the things I should pay attention to when transferring? While people start minting nfts, is any problem in any chance will appear?

**Comment by Vectorized** [comment]
This is related to OpenZeppelin's Ownable https://docs.openzeppelin.com/contracts/4.x/access-control#ownership-and-ownable, which is not covered by ERC721A. 

Transferring ownership of the contract does not affect ERC721A's functionalities. 

For marketplaces like OpenSea, you can still continue to edit the collection's page even after the ownership has been transferred. You will have to separately add your customer's address as a collaborator on OpenSea.

I would suggest discussing ownership details with your customer. 
- Does your customer know how to operate the contract? 
- Does your customer trust you to maintain the contract?
- Does your customer require different access controls for different functions? See the OpenZeppelin link for more details.
This are the business decisions that you have to sort out.

**Comment by justChargin** [comment]
You are the best. Thanks for quick answer. Have a good night and thanks a lot for your opensource codes. 💯
