### ISSUE TITLE
Totalsupply() decrements when token id is burned  (HUGE ISSUE)

### ISSUE THREAD

**Issue by jadeden1999** [chiru-labs/ERC721A#195]
require(totalSupply() + _mintAmount <= maxSupply, 'Max supply exceeded!');
using this modifier will cause you to suffer a small issue which his
if a user burns his token id total supply decrements 
causing users to mint extra nfts after your max supply 
this is a huge issue I noticed even in azukis contract

**Comment by Vectorized** [comment]
Azuki’s contract doesn’t have the burn functionality. It’s is an earlier version. 

We have a `_totalMinted` function for this now.
