### ISSUE TITLE
Pure _startTokenId()

### ISSUE THREAD

**Issue by fulldecent** [chiru-labs/ERC721A#196]
This implementation assume `_startTokenId()` will never change but it is specified as only `view`.

Maybe `pure` would be appropriate here.

**Comment by Vectorized** [comment]
`view` allows the function to read from immutable variables. One of the test mocks uses that.

**Comment by fulldecent** [comment]
I consider that a Solidity bug.

Filed at https://github.com/ethereum/solidity/issues/12829

**Comment by Cainuriel** [comment]
I get rid of this warning  ```  Function state mutability can be restricted to pure  ``` by making a real query to a variable. 

```solidity
 function _startTokenId() internal view override returns (uint256) 
    {
        return _initialId;
    }
```

**Comment by Vectorized** [comment]
@Cainuriel You can just override it as pure and return a constant (e.g. 1).

**Comment by Cainuriel** [comment]
I thought it was not correct to overwrite the modifiers of a virtual function.  Thanks for ask me.

**Comment by Vectorized** [comment]
Some of our users require the function to be view 
(e.g. on Upgradeable where an initializer must be used if customizing the return value of `_startTokenId()`).
