### ISSUE TITLE
IERC721Metadata.sol not found.

### ISSUE THREAD

**Issue by celiniz** [chiru-labs/ERC721A#198]
When I compile via npm hardhat I get this error: Error HH404: File @openzeppelin/contracts/token/ERC721/extensions/IERC721Metadata.sol, imported from erc721a/contracts/ERC721A.sol, not found.

**Comment by jasonhoi** [comment]
npm install @openzeppelin/contracts

https://www.npmjs.com/package/@openzeppelin/contracts
