### ISSUE TITLE
Metadata not shown on opensea

### ISSUE THREAD

**Issue by vishalcs106** [chiru-labs/ERC721A#204]
When I try to mint nft's,  the tokenUri returns ipfs://QmRHXZMzWSHZJQ5D9LJeQZGmSBF61EebwaSTjhNmLdvYWG/3, but it should have returned  ipfs://QmRHXZMzWSHZJQ5D9LJeQZGmSBF61EebwaSTjhNmLdvYWG/3.json
As a result I don't see token metadata on opensea

**Comment by ItsMeDogeio21** [comment]
This is not an issue with the contract, it's become the standard, OpenZeppelin's ERC721.sol behaves the same way, if you want to fix this you can reupload the metadata with the extensions removed, and in the future either use this method or override the tokenURI function
