### ISSUE TITLE
Random Mint

### ISSUE THREAD

**Issue by justChargin** [chiru-labs/ERC721A#208]
When somebody use my mint button i want him to receive a random NFT from this transaction.

When i use mint button (mintAmount = 2) my NFT's metadata's will be like,
ipfs://image_link/1.json
ipfs://image_link/2.json

But i dont want this. I want to receive my NFT's randomly. Like this,
ipfs://image_link/578.json
ipfs://image_link/877.json

I hope i was clear. How can i do that and can this process increase gas fees?

**Comment by Vectorized** [comment]
Just randomize the data off-chain before you store it on ipfs.

**Comment by justChargin** [comment]
I did but everyone can see my ipfs link. So you can take my ipfs link and see what's next NFT when you use mint button. (I dont wanna use surprise box method)

**Comment by Vectorized** [comment]
The easy way is to upload to IPFS after everyone has finish minting. 

Other options:
- Use a centralized server to reveal on the fly (make sure you check that they are not querying a unminted tokenId), and then migrate the data to IPFS after mint has finalized.
- Do all the trait randomization on-chain with Chainlink VRF.

Anyway, randomization of minting/traits is not in the scope of ERC721A.
