### ISSUE TITLE
How To Use safeTransferFrom on OpenSea Transfers?

### ISSUE THREAD

**Issue by justChargin** [chiru-labs/ERC721A#210]
When i tried to transfer my nft to my another account it using transferFrom to transfer my NFTs and my other account receive a bunch of tokens (also can you explain to me what means those tokens?) How we can use safeTransferFrom method as default for transfer transactions on OpenSea?

Here is my contract's token page (what can i do with them? Can i turn them to ethers?)
https://rinkeby.etherscan.io/token/0x71dfdcc4837f3162ed43100a5b73ac4d11069442
Here is my contract address
https://rinkeby.etherscan.io/address/0x71dfdcc4837f3162ed43100a5b73ac4d11069442

(I use safeTransferFrom method on contract for test something)

**Comment by kyokosdream** [comment]
I'm pretty sure OpenSea will automatically call `safeTransferFrom` since ERC721A implements IERC721. 

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/IERC721.sol
