### ISSUE TITLE
I cant list my NFTs on my alredy existing empty collection

### ISSUE THREAD

**Issue by justChargin** [chiru-labs/ERC721A#211]
![image](https://user-images.githubusercontent.com/46795644/160484680-d2665829-df4c-4ec1-b7ff-30dc2ddd8e56.png)

**Comment by justChargin** [comment]
My main goal is, list my smartcontract's collection on opensea without mint any nfts. I found a page that called get-listed https://testnets.opensea.io/get-listed/step-two

I tried to list my collection but it throwed that,

![image](https://user-images.githubusercontent.com/46795644/160690392-87519407-9bce-4a60-a7b2-06b23ab1caa1.png)

My contract address is: https://rinkeby.etherscan.io/address/0xC465D58d18FC6097e4ace6Ece23e20f03D52D443

**Comment by kyokosdream** [comment]
In my personal experience, you need to mint at least one token before OpenSea will show your collection.
