### ISSUE TITLE
Fix ERC721ABurnable _burn call 

### ISSUE THREAD

**Issue by kyokosdream** [chiru-labs/ERC721A#214]
#213 

Hopefully I didn't make a mistake here.

**Comment by kyokosdream** [comment]
I see that the _burn function is overloaded with a second function definition:

`function _burn(uint256 tokenId, bool approvalCheck)`

But I'm unable to compile without changing the ERC721ABurnable to use the _burn function with the single parameter:
`function _burn(uint256 tokenId)`

**Comment by Vectorized** [comment]
@kyokosdream 

Make sure your code is the latest.

If you are using hardhat, remove the artifacts and cache folder for a clean recompile.

If you are on remix, delete the erc721a directory in the .deps folder, then recompile
(you may need to close and open the .sol file again).

Sometimes, the old library files may be cached.

**Comment by kyokosdream** [comment]
I'm working on a branch of our repo that hasn't been pushed to our Github. Let me try to follow your instructions now.

**Comment by kyokosdream** [comment]
Fixed by updating from v3.0 to the latest code in repo (I assume equivalent to latest release v3.1). Closing issue and pull request.
