### ISSUE TITLE
Opensea not listing my collection

### ISSUE THREAD

**Issue by justChargin** [chiru-labs/ERC721A#215]
I want to list my smartcontract's collection on opensea without mint any nfts. We will open presale status later and people will be able to mint. After they mint, their NFT's will be listed in this collection. I found a page that called get-listed https://testnets.opensea.io/get-listed/step-two

I tried to list my collection but it throwed that,

![image](https://user-images.githubusercontent.com/46795644/160690392-87519407-9bce-4a60-a7b2-06b23ab1caa1.png)

My contract address is: https://rinkeby.etherscan.io/address/0xC465D58d18FC6097e4ace6Ece23e20f03D52D443

How can i list my erc721a contract's collection without mint

**Comment by Vectorized** [comment]
You need to mint something:

> We couldn't find this contract. Please ensure that this is a valid ERC721 or ERC1155 contract deployed on Rinkeby 
**and that you have already minted items on the contract.**

**Comment by justChargin** [comment]
> You need to mint something:
> 
> > We couldn't find this contract. Please ensure that this is a valid ERC721 or ERC1155 contract deployed on Rinkeby
> > **and that you have already minted items on the contract.**

But i want to list my collection before any mint. How can i do that? If i create my collection manually on opensea, after the first mint my collection listing on opensea with this name -> My Collection Name **V2**
Like this,

https://user-images.githubusercontent.com/46795644/160484680-d2665829-df4c-4ec1-b7ff-30dc2ddd8e56.png

Is it possible to list my collection without mint any nft?

**Comment by Vectorized** [comment]
I think this is a limitation of Opensea.

If you are afraid of name stealers, reserve the name with a empty collection first,   
and after your mints hit OpenSea, delete the empty collection and quickly rename the new collection.

If anyone knows a better way, please advise.

**Comment by kyokosdream** [comment]
I believe they get their name stolen all the time. If you search for a popular NFT project you'll find endless duplicate projects that also have the exact same images and metadata (since the underlying media asset is public and reproducible).

**Comment by kyokosdream** [comment]
Please avoid opening duplicate issues: #211 

I responded to you on the previous issue.

https://github.com/chiru-labs/ERC721A/issues/211#issuecomment-1082313565
