### ISSUE TITLE
minor nit: section tracking within documentation

### ISSUE THREAD

**Issue by andrewkmin** [chiru-labs/ERC721A#216]
Extremely minor, but I noticed that once you navigate to a subsection on https://chiru-labs.github.io/ERC721A/#/erc721a, you then become "anchored" to it such that if you want to click to jump to that same subsection later, clicks will be rendered useless (though you can refresh to jump back to that subsection if you'd like).

(one) proposed solution: dynamically update the URL based on the subsection you're currently viewing

See the following video/gif for a brief visualization of the issue:
![erc721a-gif](https://user-images.githubusercontent.com/8583903/160753475-31ef8ea3-130d-49c6-b362-e4db61c8ebe2.gif)

**Comment by Vectorized** [comment]
https://github.com/docsifyjs/docsify/issues/1780
