### ISSUE TITLE
Invalidating Addresses after Minting (uint64 aux Whitelist Slots)

### ISSUE THREAD

**Issue by kyokosdream** [chiru-labs/ERC721A#218]
We use the aux variable in our implementation to keep track of whitelist slots. We use a Merkle proof to perform whitelist verification. However, a user has brought up the strategy some bad actors have taken which goes like this:

1) Hit the maximum whitelist slot limit 
2) Transfer the NFTs to a different wallet so that their whitelisted address no longer owns any tokens 
3) Be able to whitelist mint the maximum limit again since they still belong to the whitelist and their `aux` variable is now reset to zero.

I can't think of anyway to solve this apart from storing invalidated addresses directly in contract storage (leading to high gas consumption) or to re-generate the Merkle root hash and set a new one on the contract _after every mint_ (which obviously makes no sense).

Is this just a limitation of whitelist implementations? Perhaps I'm missing something here.

**Comment by Vectorized** [comment]
`aux` should be strictly increasing only. Never reset it to zero.

**Comment by kyokosdream** [comment]
But if an address exits the project (sells or transfers all of their tokens) won't the ownership info be transferred to a new owner with the aux field initialized to 0 again? And then when they re-renter the project by doing (3) in the above comment, their aux variable will become 0 again as a new owner? 

Does that make sense? We never reset the number to zero, but won't that take place automatically when a user exits and re-enters the project?

**Comment by Vectorized** [comment]
Transferring tokens will never ever affect `aux`. You can check it in ERC721A's source code.

**Comment by kyokosdream** [comment]
Thanks for the quick response I guess I should have tested this before opening an issue. I'll close this shortly.
