### ISSUE TITLE
Contract not accepted by Opensea (despite 20 mints!)

### ISSUE THREAD

**Issue by fabioberger** [chiru-labs/ERC721A#222]
Hi there,

I've deployed my new ERC721A contract to Rinkeby (https://rinkeby.etherscan.io/address/0x72371190EF654Af32f8312966E623Dd77b66039a) and have tried to list it on Opensea testnet (https://testnets.opensea.io/get-listed) but am getting the `We couldn't find this contract. Please ensure that this is a valid ERC721 or ERC1155 contract deployed on Rinkeby and that you have already minted items on the contract.` error. I've minted 20 pieces, and even set the sale to active but it hasn't helped.

Using an ERC721 validation service shows that my contracts are compliant:

<img width="1274" alt="Screenshot 2022-03-31 at 22 16 41" src="https://user-images.githubusercontent.com/2151492/161141994-6da8917a-66fa-4c47-9c3c-7a2d815f19cb.png">

<img width="1123" alt="Screenshot 2022-03-31 at 22 16 50" src="https://user-images.githubusercontent.com/2151492/161142010-46d87614-2106-4b32-8fe7-207907380b9a.png">

Any help debugging this would be greatly appreciated 🙏

**Comment by mvillere** [comment]
Hey a bunch of people are having the same problem on opensea testnet and possibly mainnet as well. Opensea has said they are looking at it, but no resolution yet. Can check the developer channel in opensea discord to follow it.

**Comment by fabioberger** [comment]
Thanks for the reply @mvillere. Just checked that this happens with a minimal ERC721A contract and it does (https://rinkeby.etherscan.io/address/0x8A6f2e8033A2FC96Fa491a61BAE50d2d6089C1b6#code). Will follow the issue on Discord.

**Comment by mazzo007** [comment]
i'm having the same issue, i think it's realted to opensea because i tried to copy and deploy some of random contracts already available on opensea testenet and it didn't get listed

**Comment by mazzo007** [comment]
@fabioberger the one u attached got listed on opensea
[https://rinkeby.etherscan.io/address/0x8A6f2e8033A2FC96Fa491a61BAE50d2d6089C1b6#cod](https://rinkeby.etherscan.io/address/0x8A6f2e8033A2FC96Fa491a61BAE50d2d6089C1b6#code)

**Comment by mazzo007** [comment]
https://twitter.com/apiopensea/status/1509676026816729089
