### ISSUE TITLE
Collection cant get listed on opensea

### ISSUE THREAD

**Issue by justChargin** [chiru-labs/ERC721A#223]
My contract address: 

https://rinkeby.etherscan.io/address/0xe3267c394b28655a2e4cd46ddec3c4c512b0dfb1
(we already minted 17 items)

Last night opensea was down and we didn't notice it. So we mint some items and our collection not listed in opensea. Today it still can't get listed. How can we solve this?

I also tried to get listed manually by using this link -> https://testnets.opensea.io/get-listed/step-two

But it throws me an error says 
![image](https://user-images.githubusercontent.com/46795644/161328509-39d5a299-12d2-40f8-8024-0df84f4096d0.png)

In mainnetwork, if this problem appear again how can we deal with it? Is mailing opensea can solve problem?

**Comment by mvillere** [comment]
Hey, fyi, lots of other people having this problem too. Opensea testnet is messed up despite them claiming its fine. Put in a support ticket about it, but mostly we all just have to wait for them to fix it. Go to their discord and try to get help there.
