### ISSUE TITLE
I couldn't figure out how to implement erc721aburnable and use it

### ISSUE THREAD

**Issue by justChargin** [chiru-labs/ERC721A#226]
This is actually not an issue but i need to help that how can i use burn function after import it. Can someone possibly help me about that or can anyone give me an example contract that using it? Thanks.

( I know i shouldn't open this issue im sorry about that is there any forum for erc721a?)

**Comment by ahbanavi** [comment]
Just import and inherit the `ERC721ABurnable`  extension like this, and you are good to go.  
Users can burn tokens (that they owned or approved) by calling the public `burn` function implemented inside the extension. [See here](https://chiru-labs.github.io/ERC721A/#/erc721a-burnable)
```solidity
pragma solidity ^0.8.4;

import "erc721a/contracts/extensions/ERC721ABurnable.sol";

contract Azuki is ERC721A, ERC721ABurnable {
  constructor() ERC721A("Azuki", "AZUKI") {}

  function mint(uint256 quantity) external payable {
    // _safeMint's second argument now takes in a quantity, not a tokenId.
    _safeMint(msg.sender, quantity);
  }
}
```

But if you don't want people to burn their tokens, or you have something specific in mind, you shouldn't inherit from the `ERC721ABurnable` extension. You should use the internal `_burn` function instead, by calling it directly in your contract the way you wanted. [See here](https://chiru-labs.github.io/ERC721A/#/erc721a?id=_burn)

>  is there any forum for erc721a?  

The only official chat for this repo, for now, is [Azuki's Discord](https://discord.gg/azuki) dev channel.

**Comment by justChargin** [comment]
> Just import and inherit the `ERC721ABurnable` extension like this, and you are good to go. Users can burn tokens (that they owned or approved) by calling the public `burn` function implemented inside the extension. [See here](https://chiru-labs.github.io/ERC721A/#/erc721a-burnable)
> 
> ```solidity
> pragma solidity ^0.8.4;
> 
> import "erc721a/contracts/extensions/ERC721ABurnable.sol";
> 
> contract Azuki is ERC721A, ERC721ABurnable {
>   constructor() ERC721A("Azuki", "AZUKI") {}
> 
>   function mint(uint256 quantity) external payable {
>     // _safeMint's second argument now takes in a quantity, not a tokenId.
>     _safeMint(msg.sender, quantity);
>   }
> }
> ```
> 
> But if you don't want people to burn their tokens, or you have something specific in mind, you shouldn't inherit from the `ERC721ABurnable` extension. You should use the internal `_burn` function instead, by calling it directly in your contract the way you wanted. [See here](https://chiru-labs.github.io/ERC721A/#/erc721a?id=_burn)
> 
> > is there any forum for erc721a?
> 
> The only official chat for this repo, for now, is [Azuki's Discord](https://discord.gg/azuki) dev channel.


Thanks, this reply is so clear now im able to understand it. Can i kindly ask you an another question? I have two seapare contracts.

1. ERC721A NFT mint contract
2. NFT Stake contract

I need to approve both user and contract for use my NFT mint contract's safeTransferFrom method but i cant understand how to use setApprovalForAll method... How should i call it and i want this: When a user tried to stake my nft my website will look is this user approved or not. If he is approved, then he can able to stake him nfts. But he is not, then he need to approve himself by calling setApprovalForAll method.

But when a user call setApprovalForAll method how is he call it?
I mean,

![image](https://user-images.githubusercontent.com/46795644/161444984-82956c8b-7276-498c-bcc9-b8288de527cd.png)


What my user need to write there?
Own address or my contracts address?

And when i tried to approve my stake contract
what should i write there when i tried to approve my staking contract?

**Comment by Vectorized** [comment]
@justChargin 
Two steps.
1. User to call `setApprovalForAll(<address of staking contract>, true)` on the NFT contract, 
2. User to call the staking contract's function, which calls `IERC721.transferFrom(msg.sender, address(this), tokenId)`.
