### ISSUE TITLE
I cannot verify my smart contract using ERC721A implementations on etherscan

### ISSUE THREAD

**Issue by Tayarthouail** [chiru-labs/ERC721A#227]
I've used ERC721A functionality inside the smart contract perfectly but when I want to verify it on Etherscan I got an error.
Below are the imports that I used for the smart contract and I copied inside the Etherscan code

How can verify a contract with ERC721 on Etherscan?

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/finance/PaymentSplitter.sol";
import "@openzeppelin/contracts/utils/Strings.sol";
import "./ERC721A.sol";

**Comment by mvillere** [comment]
Are you using the hardhat etherscan plugin to verify? @nomiclabs/hardhat-etherscan? If not, then you should use that. You can find documentation on how to do so on hardhat's website. ERC721a verifies fine on etherscan.
