### ISSUE TITLE
DeclarationError: Undeclared identifier. -->  tokenIds[i] = tokenOfOwnerByIndex(_owner, i);

### ISSUE THREAD

**Issue by mujadmani** [chiru-labs/ERC721A#236]
I just migrated from ERC721Enumerable to ERC721A, and am currently experiencing this issue:

```
DeclarationError: Undeclared identifier.
--> example.sol:100:21:
|
100 | tokenIds[i] = tokenOfOwnerByIndex(_owner, i);
| ^^^^^^^^^^^^^^^^^^^
```

All I did was clone https://github.com/HashLips/solidity_smart_contracts/blob/main/contracts/NFT/NFT_PRESALE.sol and replaced the imports to ERC721A after uploading its "contracts" folder library to http://remix.ethereum.org/

**Comment by Vectorized** [comment]
Delete the walletOfOwner function, and use ERC721AQueryable.

**Comment by mujadmani** [comment]
> Delete the walletOfOwner function, and use ERC721AQueryable.

Thanks a lot for your reply @Vectorized.
Are you referring to: https://github.com/chiru-labs/ERC721A/tree/main/contracts/extensions)/ERC721AQueryable.sol ?

I will try this. Thanks again!

**Comment by mujadmani** [comment]
@Vectorized Thanks again. Works fine, but how do we use a similar function such as walletofOwner in ERC721A so we know the ID's addresses own??

**Comment by Vectorized** [comment]
Look into tokensOfOwner function in ERC721AQueryable.
