### ISSUE TITLE
How to mint reserved tokenIDs for specific addresses with ERC721A

### ISSUE THREAD

**Issue by zoultrex** [chiru-labs/ERC721A#238]
I have a collection where my whitelist with around 200 users will hand pick the tokens they want before the contract is deployed
They will pay zero fee for the minting, only the gas price

Since ERC721A does not implement the mint function with a tokenID (amount instead) there is no straightforward way for me to deliver these specific tokens to my whitelist

Could someone suggest a safe approach to do so? 

I will have knowledge of both the tokenIDs and their corresponding addresses, I just need to find a way to call some other custom mint/transfer function when they connect to my minting dapp

Initially I was thinking to create the collection with a max supply that does not include the 200 for the whitelist, and leave them as the last tokens on list, for example, say the entire collection has 1000 tokens, I'd put the max supply as 800, and deal with those 200 in a different way.

The easiest obvious way that I thought was to call a transfer function since I'll have their addresses, but paying gas myself for minting the 200 and then also for the transactions is a no go.

Looking at the ERC721A docs I see that the approve function could be used so that they get approved for their specific tokens and then pay for the transfer to themselves, but I would be the one to issue all the 200 approve calls and I bet this would have similar or same gas fee. I would do so only if the fees are zero or irrelevant, but I don't think I can count with that.
Also, I'm not sure if approve could work since I'd have to approve for a token that has never been minted before.

**Comment by Vectorized** [comment]
Mint the first 200 to the contract, use ERC721AOwnersExplicit to initialize the slots, and when the users mint, transfer the specific tokens to them. 

Or just directly airdrop them when the network gas is low.  

Or use OpenZeppelin or Solmate.

**Comment by zoultrex** [comment]
> Suggestions:
> 
> * Just let them mint whichever token ID that comes their turn, and set the metadata accordingly to what they have picked.
> * Directly airdrop them when the network gas is low.
> * Use OpenZeppelin or Solmate.

Thanks @Vectorized !

Could you expand on 1 and 3?

I'd assume for 1 id call some contract function to get that updated?

I checked some tutorial for soulmate and I guess you mean to call tokenURI in a way that I'd be monitoring which address minted each tokenID then assign the end of the URI to the metadata that this specific user should own to be something like URI://CID/_tokenname_.json ?

**Comment by Vectorized** [comment]
1. Say, user A has been assigned a NFT with traits (X, Y, Z), then just assign (X, Y, Z) for the metadata of their token ID.

3. Those are different implementations of ERC721 that can support assigning to arbitrary token ID during mint. You should select the tool that best fits your job. ERC721A may not be suitable for every use case.

**Comment by zoultrex** [comment]
1) I'm really not sure how you can set metadata traits in this case, if that means something to be done in the blockchain.
If it's not on the blockchain, do you mean that I should not upload the metadata json files until after the users have minted, so only after that I can figure out which token IDs those specific users have picked and then name their respective json files matching the IDs they picked? If that's the idea then that sounds very reasonable. I could override _startTokeId() to match the number of those for the whitelist. Is this more or less what you mean?

2) Thanks got it

My client has a group of premium users (those 200 from the example) that are allowed to select 1 artwork each, they participate in the creation process etc, and they get to choose which one they want. So when artwork is finished they pick one, after the collection is created and contract deployed, they should receive their respective tokens to match those artworks
