### ISSUE TITLE
We cannot verify this contract | unidentified contract error

### ISSUE THREAD

**Issue by justChargin** [chiru-labs/ERC721A#239]
![image](https://user-images.githubusercontent.com/46795644/163184388-9046c18f-9576-449d-b395-75d438dc9a29.png)

Suddenly i started to getting this error and my nft's started listing like this

![image](https://user-images.githubusercontent.com/46795644/163184523-eab20001-a89f-4d57-a18d-2ec7f6361815.png)

Also in polygon network, im not be able to approve my nfts. Transactions gettin stuck at pending.

What is happening i cant get it...

**Comment by Vectorized** [comment]
https://rinkeby.etherscan.io/address/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85#code
^ I don't think that 0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85 on Rinkeby is your NFT contract.

Your OpenSea link is viewing that contract.

I think this 0xd0dd53b77bd01a9992a8b3d5ecde29c4a9a3fdf2 should be yours:
https://rinkeby.etherscan.io/address/0xd0dd53b77bd01a9992a8b3d5ecde29c4a9a3fdf2#code
https://testnets.opensea.io/assets/0xd0dd53b77bd01a9992a8b3d5ecde29c4a9a3fdf2/0

**Comment by justChargin** [comment]
My main question is why my contracts not verified on metamask page? Why am i getting this: 
![image](https://user-images.githubusercontent.com/46795644/163189427-97baf90a-5e2d-4ba6-a271-2bdb4ad5cae9.png)

**Comment by Vectorized** [comment]
Why is your cost `40000000000000000000` wei, which is 40 ETH? 

Are you sure you want to charge 40 ETH for a NFT?

**Comment by justChargin** [comment]
I will deploy my contract on Polygon network so i wanted to set my price as 40 MATIC

**Comment by Vectorized** [comment]
I see. 

I'm able to deploy the contract and mint myself.

**Comment by justChargin** [comment]
I'm able to mint and approve myself now too but in polygon main network we cant approve our nfts because all transactions are stuck on pending. I guess there is a error about polygon network? Am i right?

**Comment by Vectorized** [comment]
Does setApprovalForAll work on Rinkeby? If so, should work fine on Polygon. 

Sometimes, it could be due to the default Metamask RPC (you may want to replace it with an Alchemy RPC).

Send me the etherscan link for the pending tx.

**Comment by Vectorized** [comment]
https://docs.alchemy.com/alchemy/guides/connecting-metamask-to-alchemy

**Comment by justChargin** [comment]
![image](https://user-images.githubusercontent.com/46795644/163197739-6a7367a0-a1d3-4731-b5b4-0b6a009593b1.png)

Im getting this error when i tried to add alchemy... ):

![image](https://user-images.githubusercontent.com/46795644/163197853-f8c1418a-8405-4fe7-8dae-41b2766df607.png)

**Comment by justChargin** [comment]
![image](https://user-images.githubusercontent.com/46795644/163202655-c8b53b5d-f4e8-4442-8629-a730878cbe7e.png)

Why my contract is not verifying? How can i fix that?

**Comment by Vectorized** [comment]
Clear / cancel your pending tx.

**Comment by justChargin** [comment]
I verified my contract with `hardhat verify` and its verified on etherscan. I still have no idea why im getting this warning for all my contracts...

Also i have an another question can i mint an nft for someone with erc721a? I mean, i mint one nft for you and this nft's owner will be you but i will pay gas-fee for you.

**Comment by Vectorized** [comment]
You can direct mint to others, but the token IDs must be in sequential order.
