### ISSUE TITLE
Feature: Add Interface

### ISSUE THREAD

**Issue by ahbanavi** [chiru-labs/ERC721A#242]
Should we consider adding interfaces for `ERC721A`, `Queryable`, and `Burnable`?  
It helps devs for external calls.  

e.g., I'm working on a Soft NFT Staker contact that calls `explicitOwnershipOf` on the main NFT contract that implemented `IERC721AQueryable`, and I have to write an Interface my own like this:  
```solidity
interface IERC721AQueryable is IERC721 {

    struct TokenOwnership {
        address addr;
        uint64 startTimestamp;
        bool burned;
    }

    function explicitOwnershipOf(uint256 tokenId) external view returns (TokenOwnership memory);

    function explicitOwnershipsOf(uint256[] memory tokenIds) external view returns (TokenOwnership[] memory);
}
```  
to use in the Staker contract like this:
```solidity
IERC721AQueryable token = IERC721AQueryable(addr);

IERC721AQueryable.TokenOwnership memory owner = token.explicitOwnershipOf(tokenId);
```  
It would be a significant help if there were in the library.  

The `ERC721A` interface could extend from OZ `IERC721` with an additional `totalSupply` and `TokenOwnership` struct.  

I'll open a PR tomorrow, but feel free to open yourself.

**Comment by Vectorized** [comment]
SGTM.
