### ISSUE TITLE
Twitter For Azuki Broken on https://www.erc721a.org/

### ISSUE THREAD

**Issue by cchen408** [chiru-labs/ERC721A#253]
# Issue
The twitter at the top right of the landing page https://www.erc721a.org/ and also on the footer at the bottom is pointing to a broken link.

I saw that we had made this fix: https://github.com/chiru-labs/ERC721A/commit/387008a2d61e057936052454b704023534f37984 for the docs but we need the same fix for the landing page.

# Screenshots

Top Right Twitter:
![image](https://user-images.githubusercontent.com/2694506/165154974-c7010a57-96f0-4ee9-b350-e733962ac2b6.png)

Footer Twitter Link:
![image](https://user-images.githubusercontent.com/2694506/165155038-70454fff-3a62-48f6-a929-297e3252164d.png)

Broken link:
![image](https://user-images.githubusercontent.com/2694506/165155430-19422f25-6990-46dc-9388-9623c5572cd0.png)

**Comment by Vectorized** [comment]
Oh ya! Thanks!!

**Comment by 2pmflow** [comment]
Fixed thanks for reporting

**Comment by cchen408** [comment]
awesome 👍
