### ISSUE TITLE
Remove dependency from @openzeppelin remapping

### ISSUE THREAD

**Issue by alephao** [chiru-labs/ERC721A#254]
Currently, the contract imports `@openzeppelin` which is the default way to import openzeppelin when using a hardhat project.

https://github.com/chiru-labs/ERC721A/blob/b738004bf6baa53d4b07fbe2aeae8f58eada97a6/contracts/ERC721A.sol#L6-L12

There are two main problems with that approach:
1. The project importing ERC721A might be using a different remapping for openzeppelin so instead of `@openzeppelin/contracts` might be `openzeppelin-contracts` or just `@openzeppelin`  or any other thing. So they will have to change their remapping to follow this project's remapping which is not a great experience.
2. The project importing ERC721A might be using a different version of `openzeppelin`, which might result in a different outcome for the contract

To support any project and to provide a better developer experience when using ERC721A, I suggest either providing a flattened version of the contract or copying the source code of the 3rd party libraries used to this project

Happy to do it myself next week if this is desirable

**Comment by Vectorized** [comment]
We have OpenZeppelin dependency on both the main repo and upgradable repo. Changes will need to be made not just in the code, but also possibly the workflow files. 

Let me ask the team for comments. @cygaar

**Comment by Vectorized** [comment]
Some reasons I'm for keeping the dependency:

- Most of the imports are interfaces.
- Avoid duplication of tests. 
- The Upgradeable repo uses the [initializable contract from OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/proxy/utils/Initializable.sol), which is written for OpenZeppelin's transpiler. 

If we were to implement this:

- We should inline only the required functions from ERC165 (like Solmate), Context, Strings (used to convert uint256 to string), Address right into `ERC721A.sol`. 
- Tests will be needed to cover the new inlined code.
- We can directly copy and paste `IERC721`, `IERC721Metadata`, `IERC165` definitions into the tentatively upcoming `IERC721A.sol` (#243).
- We don't want to introduce any new classes to avoid namespace collision with OpenZeppelin's interfaces (which are frequently used).

You can make a PR if you want, and we can consider from there. 

This may not be trivial, and there is a good chance we may end up just keeping the dependency for simplicity.

**Comment by alephao** [comment]
Thanks for checking it out. Seems non trivial, and you're right, it's unlikely to change so I the 2nd issue I mentioned is not a real problem. I'll play with it and see if I can come up with something nice. Then we can discuss in the PR!

> Most users will use the default OpenZeppelin mapping.

I see how this is true for hardhat, but In my case I use [foundry](http://github.com/foundry-rs/foundry) which is becoming very popular very quickly, so my workflow is the following:

- `forge init` to init a project
- `forge install chiru-labs/ERC721A` to install this repo
- Then I import it in a contract and run `forge build`. It crashes because it can't find `@openzeppelin`
- Then I install openzeppelin `forge install OpenZeppelin/openzeppelin-contracts`
- I run `forge build` and still crashes since the default remapping is `openzeppelin-contracts`
- I update the remapping to @openzeppelin, and all is good

Here is an asciinema with the recording. I had those issues before so I know how to solve, but it's definitely frustrating.

[![asciicast](https://asciinema.org/a/490316.svg)](https://asciinema.org/a/490316)

**Comment by ahbanavi** [comment]
@alephao I see where you coming from. 
I also use [brownie ](https://github.com/eth-brownie/brownie) sometimes and remapping is different there.  
IMO it's more like an OZ problem, I mean why is their npm package name different from the GitHub repo? all of this (apart from using a different version) could be fixed if their GitHub repo and npm package names were the same.  

IMHO in-sourcing an audited and well-tested contract like OZ might add very additional overhead for maintainers especially in the upgradable repo, keeping dependency is ok for now.  
We could update the docs and readme for foundry and brownie to how to install `erc721a` and update the remappings properly.

Might be related:
https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3334

**Comment by mpeyfuss** [comment]
I also use brownie. My brownie-config.yaml files already contains the remapping so that my projects are compatible with hardhat/truffle developers. Updating docs seems like the easiest solution IMO. Keeping OZ dependencies is a better "trust builder" as well.
