### ISSUE TITLE
Use Diamond Storage

### ISSUE THREAD

**Issue by mudgen** [chiru-labs/ERC721A#267]
It would be useful if the ERC721A implementation was changed to use [diamond storage](https://dev.to/mudgen/how-diamond-storage-works-90e).

Diamond storage is a contract storage technique that makes organizing and upgrading data in proxy contracts and [diamonds](https://eips.ethereum.org/EIPS/eip-2535) possible.

If the ERC721A implementation used diamond storage then it could be used in diamonds and other proxy contracts without change.

**Comment by cliffhall** [comment]
This is true, and one of my biggest complaints about most of the 721 implementations, they cannot be used with a diamond if they use the common storage approach. Even OZ's upgradeable suite does this. :(

**Comment by Vectorized** [comment]
https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2964

**Comment by mudgen** [comment]
> [OpenZeppelin/openzeppelin-contracts#2964](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2964)

Yes, OpenZeppelin plans to adopt diamond storage, but we don't know when that will be:

> From [frangio](https://github.com/frangio): Yes, we want to adopt diamond storage for the next major release, but we don't have an estimated release date. It will most likely happen whenever Solidity 0.9 is released, and as far as we know there is no date for that either.
