### ISSUE TITLE
Incorrect token burner being tracked

### ISSUE THREAD

**Issue by TimTinkers** [chiru-labs/ERC721A#271]
There is disagreement between a comment and the actual result of burning [here](https://github.com/chiru-labs/ERC721A/blob/becc99dd9e8b72bfd344260e4b9a46dc67e78ee1/contracts/ERC721A.sol#L497):
```js
// Keep track of who burned the token, and the timestamp of burning.
TokenOwnership storage currSlot = _ownerships[tokenId];
currSlot.addr = from;
currSlot.startTimestamp = uint64(block.timestamp);
currSlot.burned = true;
```
It seems to me that `currSlot.addr = from;` should be replaced by `currSlot.addr = _msgSender();` if the intent is to keep track of who burned the token. As it stands right now, if the burn is triggered by an approved caller and not the token owner, `currSlot.addr` is set to the token owner and not the caller who actually triggered the burn.

**Comment by Vectorized** [comment]
I will update the comment to reflect the intention correctly.
