### ISSUE TITLE
ERC721A Upgradeable Unintended Changes

### ISSUE THREAD

**Issue by kyokosdream** [chiru-labs/ERC721A#277]
https://github.com/chiru-labs/ERC721A-Upgradeable/issues/8

It seems that the upgradeable version of ERC721A has become incorrect with the latest release (v3.3.0), the Upgradeable suffix is removed and the contract has a constructor instead of an initializer. 

Was this intended? I believe it may be a mistake with the latest release. Please advise.

**Comment by Vectorized** [comment]
Thanks! Fixed in #278.
