### ISSUE TITLE
docs: Clarify `startTimestamp`, etc. may be unset for tokens minted in batch

### ISSUE THREAD

**Issue by holic** [chiru-labs/ERC721A#288]
This caught a few of us off guard when we were building some tokenomics-related mechanics.

If I mint tokens 1-10 in batch, token 1 will have `startTimestamp` set but 2-10 will not (until transferred, `_setOwnersExplicit` is called, or some other means).

Worth clarifying this in the tokenomics section of the docs: https://chiru-labs.github.io/ERC721A/#/tips?id=efficient-tokenomics

**Comment by Vectorized** [comment]
Ok, we will update the docs to recommend using `_ownershipOf` or `ERC721AQueryable.explicitOwnershipOf` to get the correct struct.

**Comment by holic** [comment]
> Ok, we will update the docs to recommend using `_ownershipOf` or `ERC721AQueryable.explicitOwnershipOf` to get the correct struct.

Amazing, thanks!

I didn't realize the latest version has ownership data normalized via `_ownershipOf`, so I'll be sure to upgrade too :)
