### ISSUE TITLE
I can't use Strings for uint256 in ERC721A 4.0.0

### ISSUE THREAD

**Issue by justChargin** [chiru-labs/ERC721A#300]
![image](https://user-images.githubusercontent.com/46795644/170885611-4376fcc0-cf1a-4d6b-9e6c-f6ce6a0ef906.png)

i cant compile it, why?

**Comment by justChargin** [comment]
i can compile this code while using ERC721A 3.3.0

**Comment by Vectorized** [comment]
@justChargin We have removed OpenZeppelin. Please use the `_toString(uint256 x)` method.

**Comment by justChargin** [comment]
![image](https://user-images.githubusercontent.com/46795644/170888385-2d879e71-0302-4eb1-87f6-a629b0a76f03.png)

okay i get it then how should i change these lines of code? In 3.3.0 they're working properly. As you can see this function taking a wallet address from me and returns me that wallet address nft's

**Comment by Vectorized** [comment]
@justChargin Remove the `tokensOfOwner` function and inherit from `ERC721AQueryable`.

**Comment by Vectorized** [comment]
I've updated the docs with the changes you need to make to migrate to version 4.x.
