### ISSUE TITLE
ERC-2309

### ISSUE THREAD

**Issue by Vectorized** [chiru-labs/ERC721A#310]
https://eips.ethereum.org/EIPS/eip-2309

**Comment by TimTinkers** [comment]
Hi @Vectorized. I'm building an NFT indexing service and am currently concerned with having to [truncate `ConsecutiveTransfer` ranges](https://github.com/ethereum/EIPs/issues/2309#issuecomment-1200068169) to prevent denial of service on operations using EIP-2309 with huge ranges. I see [here](https://github.com/chiru-labs/ERC721A/blob/dca00fffdc8978ef517fa2bb6a5a776b544c002a/contracts/ERC721A.sol#L86) that Chiru Labs has set a range limit of 5000 on the size of a `ConsecutiveTransfer`. From my denial-of-service perspective, this is obviously a good thing. Unfortunately no such limit is mandated by the EIP-2309 standard; can you help me understand why you chose 5000 for this implementation? Thanks!

**Comment by Vectorized** [comment]
5000 is the limit OpenSea supports, determined empirically. And it’s a reasonable number to prevent overflows on ERC721A.

**Comment by TimTinkers** [comment]
Thank you!
