### ISSUE TITLE
Using segment tree to store ownership beginnings

### ISSUE THREAD

**Issue by caffeinum** [chiru-labs/ERC721A#315]
https://github.com/chiru-labs/ERC721A/blob/1d868d85000881637bf28d3ab69c6774f0cfcd9f/contracts/ERC721A.sol#L212-L229

This function `ownershipOf` grows as O(n) in worst case scenarios. A possible optimization is to the store each ownership beginnings in a segment tree, with O(ln n) insert and O(ln n) read.

Tree leaves are indexed as token ids, each has a value of true/false, meaning whether this token id is a segment start or now. Tree nodes are either true/false marking whether there's a segment start under them.

Downsides:
- mint would add small extra cost of writing a ownership start on each mint into the tree
- ideally we should know total supply beforehand to know the tree root index, otherwise tree is imbalanced
- transfer is always O(ln n) if it falls outside of initialized area

Upside:
- ownershipOf worst case is O(ln n), which is much more bearable.
- if we interact with tokenId where ownership is initialized already, no need to access the tree at all.

**Comment by Vectorized** [comment]
Some projects (e.g. Goblintown) use ERC721A for only one or two mints per address.

We would want to keep minting cost as close to O(1) as possible, and optimize for the majority of our use cases.
  
There may be some projects that allow thousands of mints per address, but they seem to be the exception, not the norm.  Additionally, marketplace support for thousands of mints per transaction seem to be flaky.
