### ISSUE TITLE
Allowing general storage hitchhiking

### ISSUE THREAD

**Issue by cxkoda** [chiru-labs/ERC721A#322]
Currently, ERC721A stores `startTimestamp` efficiently with each `TokenOwnership` in storage. While this is convenient for tokenomics, for some projects it would be nice to use the respective 64 bits for something else. More flexibility could be achieved by splitting the data providing logic (currently `block.timestamp`) into an own internal virtual function that is called on each transfer and renaming `TokenOwnership.startTimestamp` to something more generic like `TokenOwnership.extraData`.

Before submitting a PR, I wanted to check if this is something that you would like to support or if this is beyond the scope of ERC721A.

**Comment by cxkoda** [comment]
Oh sorry, I should have been more explicit. I was only talking about lazy-initializable data, e.g. using the blocknumber, or parts of the blockhash instead of the timestamp.

So on transfers having something like
```js
...
_packedOwnerships[startTokenId] =
    _addressToUint256(to) |
    (_extraData(from, to, previousExtraData) << BITPOS_START_TIMESTAMP) |
    (_boolToUint256(quantity == 1) << BITPOS_NEXT_INITIALIZED);
...

function _extraData(address from, address to, uint64 previousExtraData) internal view virtual returns (uint256) {
   return block.number;
}
```

My usecase is for generative art, where we want to generate and store a random seed on mint. Using this scheme, we would generate a proto-seed for each batch, and calculate the actual seed of each token later via something like `keccak(proto, tokenId)`. I'd override the above function to generate something new on mint, and reuse the previous value on transfers.

**Comment by cxkoda** [comment]
Yes this will absolutely be a breaking change because `startTimestamp` needs to be renamed. Maybe to something like `extraData`? It would be very similar to the `aux` for `addressData` in a sense (only lazily initialized). 

I submitted a quick draft implementation in #323 to show you more in more detail how I intended this. Also talking code is easier most times. IMO, it can be added pretty straightforwardly without any overhead in terms of gas (the report remained completely unchanged on my end) and only small overhead in terms of maintainability (2 extra functions).

But I understand that this might be a feature that you don't necessarily want to support/maintain upstream. In that case I'll gladly fork.

**Comment by cxkoda** [comment]
Awesome! Then I'll clean it up a bit and add some more comments and tests in the next days.

Regarding release, I totally understand! Happy if it gets considered for the next major version.

**Comment by Vectorized** [comment]
I'm thinking if 24 bits of `extraData` is enough. That's 16777215 values.

**Comment by cxkoda** [comment]
Could still be ok for some cases - but it's definitely not ideal.

For some reason I only noticed just now that there are actually 88bits of space that can be used. So I guess you were also thinking in the direction to just keep the 64bit for the `startTimestamp` and add `extraData` in the remaining 24, right?

I think that would be a good compromise to add the feature while maintaining backwards compatibility for now. Then we can expand it to the full range later if we want. If you want, I can update the PR to cover this tomorrow.

**Comment by Vectorized** [comment]
Let’s start with using the last 24 bits first. 

At least the whole word can be used. 

Tbh, I’m reluctant to break compatibility with previous versions. Cuz some people might have built functionality around `startTimestamp`.

**Comment by cxkoda** [comment]
Jup, that can very well be. I'd be curious if we could get some numbers or feel for the impact of such a change.

But also if there are some people using building on top of this - I think the migration would be fairly simple. In the end it's just renaming a variable because the underlying behavior still defaults to the same. 

I updated the PR as discussed.

**Comment by Vectorized** [comment]
Let's close this issue for now. 
If there is a need to extend the functionality in the future, we will re-open.
