### ISSUE TITLE
use soulmate

### ISSUE THREAD

**Issue by AndreiD** [chiru-labs/ERC721A#33]
what do you think about integrating this -> https://github.com/Rari-Capital/solmate/tree/dd13c61b5f9cb5c539a7e356ba94a6c2979e9eb9

**Comment by chiru-labs** [comment]
Please clarify what you mean.  -2pm

**Comment by davidlee1435** [comment]
Directly using solmate here doesn't make sense because both this project and solmate have competing implementations of ERC721. That being said, there are definitely some optimizations in solmate that could be ported over here (one of which is: https://github.com/chiru-labs/ERC721A/pull/35)

**Comment by chiru-labs** [comment]
Closing because unclear, and @davidlee1435 's PR has been merged
