### ISSUE TITLE
nfts are not viewable on opensea in latest erc721a version 4.0.0

### ISSUE THREAD

**Issue by muneebsoftblock** [chiru-labs/ERC721A#338]
nfts are not viewable on opensea in latest erc721a version 4.0.0

**Comment by Vectorized** [comment]
Post etherscan link with verified code

**Comment by intenex** [comment]
I had the same issue; if it was something similar, it might have been overriding supportsInterface for something like ERC-2981 that no longer works as it used to because OpenZeppelin is no longer supported https://chiru-labs.github.io/ERC721A/#/migration?id=supportsinterface
