### ISSUE TITLE
I can't use tokensOfOwner in my contract

### ISSUE THREAD

**Issue by justChargin** [chiru-labs/ERC721A#349]
![image](https://user-images.githubusercontent.com/46795644/175307105-d488de88-0406-4b72-a3b7-123d3a514e7b.png)

![image](https://user-images.githubusercontent.com/46795644/175307171-59936650-c6de-4659-8773-a37a7e7b9c44.png)

Why can't i use tokensOfOwner in my contract?

**Comment by justChargin** [comment]
> You can reference it like this
> 
>         IERC721AQueryable token = IERC721AQueryable(address(this));
>         uint256[] memory _tokensOfOwner = token.tokensOfOwner(_owner);
> 
>        // now you can use or return this array ===>   _tokensOfOwner
> 

Thanks a lot but why i cant use it without interface? Because i can use _safeMint without an interface. Im a self-learner and im not native at English so i mostly learning with asking instead of reading docs.

**Comment by jdutchak** [comment]
Because its an external function vs a public or internal function

**Comment by jdutchak** [comment]
function tokensOfOwner(address owner) external view returns (uint256[] memory);
}

**Comment by jdutchak** [comment]
Your already getting the tokens by owner using tokensOfOwner(_addr) ?? If they exist you have met the requirement for "... can claim"

also ownerOf is a public function so you dont need to add LKAJ.ownerOf(...) just ownerOf(...)

**Comment by justChargin** [comment]
I deleted my post when i realised that and you instantly replied :D thanks anyway

**Comment by Vectorized** [comment]
Best practice is not to call `tokensOfOwner` on chain. It is very gas expensive.
This is why we made it `external`.

Call it off-chain, and pass back only the data you need into another function to verify it.
