### ISSUE TITLE
Minting for another wallets (airdrop)

### ISSUE THREAD

**Issue by justChargin** [chiru-labs/ERC721A#351]
![image](https://user-images.githubusercontent.com/46795644/175770173-39055c8e-bd08-47b4-8557-d4234cc261b0.png)

Can i use the _safeMint function like that? It will be a safe method in real scenario? I want to mint for another wallets by paying gas for them. Will there any problem occur with this method?

**Comment by Vectorized** [comment]
Yes, you can.

**Comment by justChargin** [comment]
I want to pass a value to this function like,

function mint(address[] memory _addresses, uint[] memory mintAmount)

addresses and mint amounts that they earn from our giveaways. How can i pass this kinda value to any function?

**Comment by Vectorized** [comment]
Yup, just pass in two arrays of the same length.

**Comment by justChargin** [comment]
One last question and i know these are not related to erc721a and i apologize for that.

![image](https://user-images.githubusercontent.com/46795644/175770779-2a333903-5ca3-42fb-9120-cf8ab74c5834.png)
![image](https://user-images.githubusercontent.com/46795644/175770787-47c6b2a9-1b39-434a-af8d-476ac03df732.png)

Will whitelisted users pay much money to gas while using whitelistMint button? I usually use merkle tree but i have to give it this practice a try. What do you think?

Also while i set 100-200 wallets by using setWhitelist function will i have to pay huge money to gas?

**Comment by Vectorized** [comment]
For whitelist, you may wanna check out using MerkleProof or ECDSA. Otherwise, storing hundreds of addresses on-chain is going to cost quite a bit of gas. 

https://link.medium.com/S5qmiJLp9qb
