### ISSUE TITLE
Some base functions are not virtual and thus can't be overridden by default. 

### ISSUE THREAD

**Issue by Sdocquir** [chiru-labs/ERC721A#358]
Some base functions are not virtual and thus can't be overridden by default. 
For example, ownerOf(), balanceOf(), etc.
Is there any reason behind that design decision ? Openzeppelin has theirs all virtual to allow the most amount of extensions/customizations.

I have a use case for an extension to ERC721A that would involve modifying the logic post-mint. I'm fine with simply changing those functions to virtual in my source code, but was also wondering if there's more to that design decision that I might be missing.

**Comment by Vectorized** [comment]
Just a disclaimer, we will very most likely reject extension proposals though.

**Comment by Sdocquir** [comment]
We're writing this extension for our project.
I understand modifying those base functions could be considered to be outside the purview of an extension and might warrant maintaining a separate standard altogether, but I figured it wouldn't hurt to start with a proposal and get community feedback.

No worries if/when it gets rejected.
