### ISSUE TITLE
Use same image across all NFTs

### ISSUE THREAD

**Issue by karooolis** [chiru-labs/ERC721A#367]
ERC721A works perfectly for collections that use images stored off-chain where each image is denoted by token ID. However, for my use case I am setting an on-chain SVG image that's the same for all NFTs. Here is an example of how it works with standard ERC721 https://polygonscan.com/address/0xf81789AB209ac710bF2e0a7a9c24e8ceEB1cb368#code. I couldn't figure out though is there a way to achieve the same with the original ERC721A implementation? Otherwise, seems like forking the contract and adapting `mint` function is the best route.

**Comment by Vectorized** [comment]
Override `tokenURI` to make it return the same string of the `tokenId` exists.

Please don’t store the same string for all the tokens. The gas usage will explode.
