### ISSUE TITLE
Etherscan token tracker tagging contract as ERC20

### ISSUE THREAD

**Issue by ICJR** [chiru-labs/ERC721A#369]
https://etherscan.io/token/0xbd0766b0f10e778e1861e0e9cdcef4113683b15f

Small text next to `Overview` title lists the contract as an ERC20 token while Azuki contract https://etherscan.io/token/0xed5af388653567af2f388e6224dc7c4b3241c544 displays properly as an ERC721. 

Using latest ERC721A release. 

Is this manually defined metadata that just defaults to ERC20? Shouldn't they check `supportsInterface`? Or is this somehow related to OpenSea Issue #354 I also had a problem importing the NFT into OpenSea. Staff had to manually create the page for me.

**Comment by Vectorized** [comment]
The `supportsInterface` is overridden wrongly.

**Comment by ICJR** [comment]
-_- completely missed that when reviewing docs... thank you
