### ISSUE TITLE
Hitting the Spurious Dragon limit

### ISSUE THREAD

**Issue by agamanin** [chiru-labs/ERC721A#37]
Hi. I'm learning ERC721 implementations now and I was going to adopt the ERC721A in my smart contract. So I updated my OZ-based implementation a bit to switch to the ERC721A. The issue I face is the contract size limit:

`Warning: Contract code size exceeds 24576 bytes`

I use Harhat, no other config parameters were changed, so my contract compiles just well with OZ, while failing to fit the size with ERC721A. My SC is fairly simple, just inheriting the base implementation and introducing a few additional variables and methods. Just about 200 lines including the blank lines and comments, so I didn't expect it to exceed the size. Any advice, please?

Disclaimer: I'm not a professional Solidity developer, so it can be just something on the very surface, but I don't see it.

**Comment by AndreiD** [comment]
it's not the contract size that exceeds, it's some other error and it's bad error messages from something else. check the private keys, rpc urls,  **try with ganache instead of hardhat. ....**

**Comment by chiru-labs** [comment]
This is unexpected if your derived contract is that small. Does it go away if you compile with `runs` set to a higher value?

**Comment by jadeden1999** [comment]
try optimization 200 or 300

**Comment by agamanin** [comment]
Thanks for the advice. I tried with runs set to 1, 10, 100, 200, 300 and 500. Same result.
Probably the next step would be to try a not-hardhat environment.

**Comment by jadeden1999** [comment]
If you want share with me your code I can try running it on remix and tell you.
Also is it a flattened contract?

**Comment by weedenrj** [comment]
I had a similar issue with my hardhat environment. my solution was to keep bumping up the optimizations in my hardhat.config file until it worked. I haven't deployed to mainnet yet but I'm curious to know if there's any obvious downfall to this approach?
