### ISSUE TITLE
ERC721A address packing and any EVM changes increasing the address bits length

### ISSUE THREAD

**Issue by 0x0-github** [chiru-labs/ERC721A#382]
Hi, I'm totally fan of your work so even if you must hear it all the time, again well done and thanks for that, you all can be proud of yourselves.

Just wondering since the number of addresses is supposed to grow, following the adoption, what would happen if someday address size is increased to 256 bits. With the ERC721A as of today, I think there will be some problems for the approve / transfer mechanisms since we would compare the 160 bits of the address padded with zeros to the 256 bits length msg.sender.

I was thinking about an easy "potential fix" (since nothing guarantee that it will happen), by updating the _msgSenderERC721A() function body with:
return address(uint160(msg.sender));

It's definitively not a clean and sexy trick, but this would make sure even if addresses end up using more bits to store in the future, that the deployed contracts will still be usable.
This assumes they keep backyard compatibility on address and uint160 cast, otherwise working with bytes / masking or so should do the trick.

I was also thinking about some extra solutions, giving the ability to update the address mask, and keeping some blank space after the address bits from _packedOwnerships. But this would require more changes and will force to give up on startTimestamp and/or extraData fields.

Best regard

**Comment by Vectorized** [comment]
Are you perhaps referring to the piece of psyops that is going around?

https://twitter.com/12yearoldwithcc/status/1548841909082214400

160 bit addresses can store 2**160 - 1 numbers.

That is 1461501637330902918203684832716283019655932542976.

It is estimated that the Earth contains 133000000000000000000000000000000000000000000000000 atoms.

This number is so huge that even if you can somehow every single atom on earth to store a bit, you will run out of atoms to use.

**Comment by Vectorized** [comment]
I think predicting how Ethereum and computing will evolve is beyond my scope. 

Perhaps some quantum breakthrough may require a change in the future. 

I’ll ask around. Hopefully people more familiar with such stuff and provide new insights.

**Comment by sillytuna** [comment]
There is thinking behind the quantum issue but for the time being quantum attacks are the domain of large state actors and companies. They do (I'm told) have some amazingly powerful gear now.

re: address expansion - anything like that will break all contracts. Solidity too will mask off the same bits in any existing contracts AFAIK. There are things to concern ourselves with and things not to. This is in the not category :)

Any change from 160 bits is such a fundamental break that you're talking a new chain or a very, very long lead time with a migration strategy.

**Comment by 0x0-github** [comment]
Ok get it!
Thanks for your time and your explanations 🙏👌.
Wishing you luck and success for your future developments 💪👋.
