### ISSUE TITLE
Why TokenApprovalRef is struct with single member

### ISSUE THREAD

**Issue by jaglinux** [chiru-labs/ERC721A#383]
https://github.com/chiru-labs/ERC721A/blob/5e70c800f5ca0fd81153a0698617a28e8a3778a3/contracts/ERC721A.sol#L38

I did not intend to raise an issue, but I do not see discussion option in github !
As the title suggests, why use a struct to hold only one member. If there are 2 member variables to hold, then it makes sense to pack into struct to hold 256 bits.

**Comment by Vectorized** [comment]
This struct was introduced as a workaround for a compiler error.

See #364.

**Comment by jaglinux** [comment]
Interesting, thanks
