### ISSUE TITLE
Get token ids from address in ERC-721A contract

### ISSUE THREAD

**Issue by willindt** [chiru-labs/ERC721A#399]
Is there any way to get token ids from address in ERC-721A?
Something like walletOfOwner(tokenOfOwnerByIndex of IERC721Enumerable).

**Comment by Vectorized** [comment]
Yes, you will need the `ERC721AQueryable` extension. 

And then you can use the `tokensOfOwner` function which returns an array of token IDs.

**Comment by cygaar** [comment]
Closing because @Vectorized answered the question
