### ISSUE TITLE
Add OpenSea Whitelisting

### ISSUE THREAD

**Issue by d3or** [chiru-labs/ERC721A#40]
From [OpenSea docs:](https://docs.opensea.io/docs/1-structuring-your-smart-contract#opensea-whitelisting-optional)

> The ERC721Tradable and ERC1155Tradable contracts whitelist the proxy accounts of OpenSea users so that they are automatically able to trade any item on OpenSea (without having to pay gas for an additional approval). On OpenSea, each user has a "proxy" account that they control, and is ultimately called by the marketplace contracts to trade their items.

This will save a lot of gas, should definitely be added, and is not very difficult to add.

**Comment by chiru-labs** [comment]
This may be controversial, but I'd rather OpenSea whitelisting not live in 721A for the following reasons:
- for a base standard, it feels strange to bias towards a single marketplace over others
- there have been many phishing attacks recently and some users value the ability to revoke approval post-transaction to drop that attack vector surface area
- does not "feel" web3 as owners no longer have control over which contracts can operate on their token. Similar to how most users use browsers with js/cookies, but browsers still lets users disable js/cookies if the user chooses to

Projects can still override isApprovedForAll if they want to in the inherited contract.

- 2pm
