### ISSUE TITLE
Can someone please explain this small bit of assembly?

### ISSUE THREAD

**Issue by KamaDeFi** [chiru-labs/ERC721A#401]
In the function `_checkContractOnERC721Received`:

`revert(add(32, reason), mload(reason))`

**Comment by Vectorized** [comment]
revert takes in two args. 

The first is the offset of the revert’s data string or bytes. 

The second is the length of the revert data (in number of bytes).

What this piece of code does is essentially “bubble up” whatever error message or custom error selector (4-bytes) that the receiver revert.

**Comment by KamaDeFi** [comment]
Doesn't `mload(reason)` return the contents of `reason`  (the 4-bytes error message itself)?

How is it then being used as the length in the second argument of `revert`?

My current understanding is that this line should instead just be:

`revert(reason, 32)`

Which according to the documentation of `revert` in https://docs.soliditylang.org/en/v0.4.24/assembly.html - should return  mem[p..(p+s))] and bubble up the error message.

**Comment by KamaDeFi** [comment]
Or perhaps `reason` is encoded such that the first 4 bytes of it contain the length of the error message, and the remainder is the actual error message. That actually makes sense!

**Comment by KamaDeFi** [comment]
To clarify for future readers:

`reason` is encoded as such:

[error message][length of error message]
|------x bits-----|----------32 bits---------|

`mload(reason)` returns x, which is the length of the error message.
`add(32, reason)` returns the address of where the error message begins (after the 32 bits that contains the length of the error message).
`revert(add(32, reason), mload(reason)` then returns the error message itself.

**Comment by Vectorized** [comment]
Lengths are always 32 bytes. 

Function and error selectors are always 4 bytes. 

When you revert with a plain custom error without arguments, it’s actually `mstore(0, selector) revert(0x1c, 0x04)` under the hood. 

Also, the example used in the try-catch code is 
 different from how you will bubble up reverts in pure assembly (no try-catch).
