### ISSUE TITLE
Unable to Import Deployed Goreli Contract Into OpenSea 

### ISSUE THREAD

**Issue by advra** [chiru-labs/ERC721A#411]
I made a contract based off  erc721A 4.x. I deployed it to Goreli and minted fine. I wen to opensea to import the contract and when trying I ran into the notorious error "We couldn't find this contract. Please ensure that this is a valid ERC721 or ERC1155 contract deployed on Goerli and that you have already minted items on the contract".

![image](https://user-images.githubusercontent.com/1753803/185723183-0117d482-b2ca-4e0e-90a5-683ae3c23248.png)

So I deployed a lean contract based off  721A and arrived at the same error when trying to import it to opensea. Heres the deployed small contract address on [Goreli Etherscan](https://goerli.etherscan.io/address/0x2307f29b0e5ff50f2c5e27a140a71bbcbfc4764c).

Anyone else ran into this issue lately?

**Comment by advra** [comment]
Looks like same issue with #354. Any new developments on this? Looks like somewhere in 721A v4.x the contract cannot import to opensea? Im using `"erc721a": "^4.2.2",`

**Comment by Vectorized** [comment]
After a lil try and error, it seems that OpenSea will check if the tokenURI does return a non-empty string before considering the contract as valid. 

Try this:

```Solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

import "@openzeppelin/contracts/access/Ownable.sol";
import "erc721a/contracts/ERC721A.sol";
import "solady/src/utils/LibString.sol";

contract TryThis is ERC721A, Ownable {
    string private _tokenURI;

    constructor() ERC721A("Try", "THIS") {
        _tokenURI = "https://ikzttp.mypinata.cloud/ipfs/QmQFkLSQysj94s5GvTHPyzTxrawwtjgiiYS2TBLgrvw8CW/{id}";
    }

    function mintMulti(uint256 quantity) public virtual onlyOwner {
        _mint(msg.sender, quantity);
    }

    function _startTokenId() internal view virtual override returns (uint256) {
        return 1;
    }

    function tokenURI(uint256 tokenId) public view override returns (string memory) {
        if (!_exists(tokenId)) revert();
        return LibString.replace(_tokenURI, '{id}', _toString(tokenId));
    }

    function setTokenURI(string calldata value) external onlyOwner {
        _tokenURI = value;
    }
}```

**Comment by advra** [comment]
Hmm. I've reevaluated my original contract (https://goerli.etherscan.io/address/0xbeb9ab39d45672af96b634232141dfdf131cde84) which has a mapping id->uri. The uri is passed in mint()for each NFT.

So it should be valid as a URI is passed with querying tokenURI.

I've contacted opensea but it's been days with no response unfortunately.

**Comment by advra** [comment]
I've contacted opensea but it's been days with no response unfortunately.

Does anything in the second contract I linked have any implementation issues that opensea doesn't like?

**Comment by Vectorized** [comment]
Try Rinkeby Opensea.

**Comment by advra** [comment]
Wow that actually worked. Maybe opensea's checks on Goreli need to be updated on their end. 

Thanks again @Vectorized. Closing this as its now resolved.
