### ISSUE TITLE
Feature Request: ERC-721 and 1155 Transfer Block-Lists for certain contracts

### ISSUE THREAD

**Issue by sterlingcrispin** [chiru-labs/ERC721A#416]
**🧐 Motivation**
Recent actions by SudoSwap and now X2Y2 marketplaces are aggressively moving towards circumventing the NFT royalty system, which has largely been an honor system up until this point. Creators of NFTs should be given tools to easily cut off bad actors and control how their tokens are used. 

[EIP-2981 ](https://eips.ethereum.org/EIPS/eip-2981) is one step towards addressing this problem, but royalties will remain optional. Because of this, I suggest a transfer-level block list should become an adopted standard.

Beyond the royalty issue, generally speaking, creators should be given more control over who is allowed to operate on their tokens. The concept of permissionless tokens is nice in theory, but bad actors do exist, and giving creators control to cut them off is important.

I've also requested this of [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3655) ,

**📝 Details**
I recommend editing ERC721A contract to easily allow creators to define block-listed addresses. For example, when `beforeTokenTransfer` is called, the function would iterate through blocked addresses and require that the `msg.sender` was not equal to one of these blocked addresses.

Here's one example in an inherited contract showing how a block list might be implemented. I'm sure there are better ways, but it would be great to see this added to the core contract

    address[] public blockedAddrs;

    function populateBlockedAddrs(address[] memory addrs) public onlyOwner{
        blockedAddrs = addrs;
    }
    
    function _beforeTokenTransfer(
        address from,
        address to,
        uint256 tokenId
    ) internal virtual override(ERC721, ERC721Enumerable) {
        uint256 limit = blockedAddrs.length;
        uint256 i = 0;
        while(i < limit){
            require(msg.sender != blockedAddrs[i], "blocked address");
            unchecked {
                i++;
            }
        }
        super._beforeTokenTransfer(from, to, tokenId);
    }

Thanks for the consideration

**Comment by Vectorized** [comment]
From an efficiency point of view, this can be better implemented as a centralized on-chain registry, or multiple centralized on-chain registries (like ad-block lists), that any ERC721/ERC1155/ERC20 can query and use to block transfers. 

Otherwise, we will have to duplicate and store the entire OFAC sanction list for every newly published contract. That costs a lot of gas.

As this is out of scope, and can be implemented way more efficiently with another method, we are not in favor of adding this to ERC721A.

Thanks!

**Comment by peetzweg** [comment]
How about tackling this issue the other way around with an `allowlist`. Both solutions are not optimal anyways, but at least the collection owner just needs to take care of the allowed platforms instead of constantly newly deployed marketplaces.

**Comment by sterlingcrispin** [comment]
> users will have to write many addresses (e.g. OFAC sanctions list) to storage for every newly published contract. That costs a lot of gas.

Isn't this is another good reason to have it within each ERC721A contract? Because a sanction in Country A may not be valid in Country B. So you'd want the creator to be able to make their own block list and update it over time.

Can you please elaborate on why you are against this feature request? Beyond the registry issue there are a lot of reasons why a creator might need to block an address 

> How about tackling this issue the other way around with an `allowlist`. Both solutions are not optimal anyways, but at least the collection owner just needs to take care of the allowed platforms instead of constantly adding newly deployed marketplaces to a blocklist.

No, because you'd have to add every ETH wallet that could ever exist into the allow list

**Comment by myssynglynx** [comment]
> No, because you'd have to add every ETH wallet that could ever exist into the allow list

A basic contract check (e.g. `address(_msgSenderERC721A).code.length == 0`) could be used to ensure any external contract call for the transfer is executed by an allowlisted contract, bypassing the allowlist check if the caller is a wallet. This would increase gas cost if implemented, but it would ensure safety for any wallet-to-wallet transfer, while also ensuring that any AMM or Atomic Swap function called by a contract in the allowlisted registry is also safe.

EIP2981 can be ignored, but attempting to bypass it would require trusted transactions, since an external contract that isn't on the allowlist couldn't facilitate a trustless transaction without reverting. If ignoring EIP2981 has to be split into two trusted transactions, an ETH transaction is expected in return then it's trusted and the ETH sender could just rug them after receiving the token (or the token sender could rug the ETH sender after receiving the ETH).

**Comment by sterlingcrispin** [comment]
One argument I've seen on twitter against this is that it shouldn't be always-on by default. I totally agree with that. There should be a way to specify as the deployer of a contract if you want this functionality or not.

Maybe it becomes a true-false variable during deployment in the constructor or something.

**Comment by Vectorized** [comment]
Integrating a centralized registry can be done in just a line in ERC721A. 

For maintability, we won't accept implementations that are just a couple of lines.

```Solidity
function _beforeTokenTransfer(
    address from,
    address to,
    uint256 tokenId
) internal virtual override(ERC721, ERC721Enumerable) {
    if (blockedAddressesRegistry.isBanned(msg.sender)) revert();
    super._beforeTokenTransfer(from, to, tokenId);
}
```

The implementation of the registry is not within the scope of ERC721A.

**Comment by sterlingcrispin** [comment]
Why wouldn't that registry just be an array within the contract?

Denying a feature due to the complexity of its implementation is a poor reason. This has large scale user value.

Ask any NFT creator, "Would you like people to deny paying you a royalty? Would you like more control over how people are allowed to operate on your NFTs?" They will overwhelming support this feature

**Comment by Vectorized** [comment]
Your implementation scans through an entire array. 

Each element scanned takes 2100 gas. 

----------------------

There are many things with large scale user value -- NFT marketplaces, cancer research, solving world hunger.   
Unfortunately, they are not under the scope of efficient ERC721 batch minting.  
Including them will dilute the focus of this repo.

**Comment by sterlingcrispin** [comment]
I am 100% in agreement you should not use my implementation, it was just a conversation starter. I'm unclear the best way to implement this.

NFT Marketplaces, cancer research, etc are outside the scope of this repo.

Having a deny list during transfers, is within the scope of this repo. It's not a huge sprawling new direction its a very small change

**Comment by paulmillr** [comment]
@sterlingcrispin you should get out of eth, you're not welcome in our community with these baffling censorship proposals. Maybe work on some fintech, they would love your ideas.

**Comment by edsonayllon** [comment]
> Why wouldn't that registry just be an array within the contract?
> 
> Denying a feature due to the complexity of its implementation is a poor reason. This has large scale user value.
> 
> Ask any NFT creator, "Would you like people to deny paying you a royalty? Would you like more control over how people are allowed to operate on your NFTs?" They will overwhelming support this feature

I don't think using the reasoning of royalty bypass is sufficient reasoning for adding an alow list. Allow lists are very centralized. The owner could block addresses without needing a reason, increasing censorship. 

If royalties are a concern, it should be dealt by creating on chain royalties. Instead of choosing favorites for marketplaces in the open market. 

I don't think royalty chasing is sufficient justification for including a mechanism that greatly increases financial censorship

**Comment by sterlingcrispin** [comment]
Yeah you're right, I posted this in an emotional state reacting to what I felt like was an unjust situation, but long term this would case more problems than it solves. Sorry about that.

**Comment by deanpress** [comment]
> I don't think using the reasoning of royalty bypass is sufficient reasoning for adding an alow list. Allow lists are very centralized. The owner could block addresses without needing a reason, increasing censorship.

If marketplaces deliberately circumvent the existing royalty system which was made specifically for a convenient user experience, then I think it's fair that they can expect a solid multisig DAO, operated by several reputable NFT projects, to vote that contract's address into a filter mapping.

The DAO contract would expose a function that simply reverts if a checked address matches the filter, which NFT contracts can integrate (by checking the `to` address on `_beforeTokenTransfer()`).  If a protocol then adds royalties later, they would be removed from the list.

This should obviously not to be integrated into any standard and instead be offered as an external call function that any contract can integrate in their `_beforeTokenTransfer()` function.

The existence of such a filter list alone, along with a very small number of projects supporting it, should be enough for most serious protocols to stop circumventing royalties for the sake of delegating more fees to themselves. It would no longer be worth the risk.

**Comment by deanpress** [comment]
If anyone would like to discuss the potential solution of a DAO-operated contract extension, I drafted a contract + set of extensions here: https://github.com/deanpress/OCF-DAO
