### ISSUE TITLE
Errors at erc721a source code

### ISSUE THREAD

**Issue by justChargin** [chiru-labs/ERC721A#429]
Hey i tried to look at the erc721a source code in remix.ethereum but the website showed me some errors should i worry about them?

![Screenshot_1](https://user-images.githubusercontent.com/46795644/193429659-8f216fd3-d678-4577-807e-e838f5746bb0.png)

![Screenshot_2](https://user-images.githubusercontent.com/46795644/193429662-b3c71604-127b-433e-b30b-4e72199e3cd1.png)

![Screenshot_3](https://user-images.githubusercontent.com/46795644/193429665-b864ada4-a87a-4138-842d-1a9752a4bdc7.png)

**Comment by Vectorized** [comment]
https://twitter.com/optimizoor/status/1566738490460553218 See the suggestion. 

Nothing to worry about.
