### ISSUE TITLE
Your NFT bots are spamming Twitter. Ask them to withdraw

### ISSUE THREAD

**Issue by paulmillr** [chiru-labs/ERC721A#442]
Posting this here for developers to boycott your projects, fork them, go elsewhere from the repos.

Your NFT bots are spamming Twitter. This is not acceptable: https://twitter.com/leashless/status/1612841794999574528

Even if you did not do this, make an official statement that you're unrelated to the spam wave. It affects most huge accounts in ETH community.

![FmH295LXwAE2Y4E](https://user-images.githubusercontent.com/574696/211839210-7f635467-e970-4456-ac32-f0a873c07ce3.jpeg)

**Comment by Vectorized** [comment]
These bots will simply use any popular NFT PFP. 

Just block notifications from non-followers.
