### ISSUE TITLE
Question/Change Request: Init `currentIndex` with 1 instead of 0

### ISSUE THREAD

**Issue by Pczek** [chiru-labs/ERC721A#45]
We've been using ERC721A in our latest NFT drop. It worked great, however, having the token indexes start 0 caused some edgecases in our other contracts for the token with the id 0.

For example we have a simple staking contract were we map the owner address to their staked token. Each address can only stake a single token so its a `mapping(address => uint256) ownerToToken`. However, each address of the map get's initialized with `0` by solidity afaik. So doing stuff like `require(ownerToToken[msg.sender] == 0, "Already staked a token");` does not work properly when supporting the token id 0 in the ERC721A contract.

**Comment by chiru-labs** [comment]
Yup this is on the roadmap. Feel free to open a PR if you have one ready!

**Comment by Pczek** [comment]
👍 Started working on a PR.

**Comment by Pczek** [comment]
Will leave the PR link here as a reference. It's not finished yet. Had only limited time today.
Let me know what you think about the renaming of the variable and it's use.

https://github.com/chiru-labs/ERC721A/pull/66

**Comment by Pczek** [comment]
PR is ready for review. ✌️ 
https://github.com/chiru-labs/ERC721A/pull/66

**Comment by ottogutierrez** [comment]
Quick question about this, if this PR gets approved, the default behaviour would be for the index to start at 1 right?

**Comment by VRPunk9036** [comment]
Wow great work @Pczek , I will do some tests with this to use on one of my projects! Collections starting with 1 are a lot less confusing

**Comment by Pczek** [comment]
> Quick question about this, if this PR gets approved, the default behaviour would be for the index to start at 1 right?

Yes. Having token id `0` can lead to confusion in smart contracts as the initial value for `uint` is `0`.

**Comment by jpegdigital** [comment]
Does function tokenByIndex(uint256 index) need to be adjusted? Token at index 0 is now tokenId 1.

Something like `return index + 1`.

**Comment by Pczek** [comment]
@jpegdigital yes you are right. I've adapted it in my PR.

Fixing this, i've stumbled over the `tokenOfOwnerByIndex` function. Which also seems to need an adaptation. I've added a test for it in my PR however, it's failing and I'm not yet sure what do adapt. Not yet had the time to wrap my head around the `ownership` mapping in the code. 🤔 

https://github.com/chiru-labs/ERC721A/blob/main/contracts/ERC721A.sol#L85-L108

**Comment by Pczek** [comment]
Fixed the `tokenOfOwnerByIndex` function now as well. I wrote some test for the. The PR #66  is ready for review, happy to get some feedback and merge it if approved. 👍

**Comment by Pczek** [comment]
After some rework #66 is again ready for a second review before merging it.

**Comment by kyokosdream** [comment]
Since the Hashlips library which has a large following and is used by many beginners to help programatically generate artwork begins indexing at 1, we followed the OPs suggestion and begin indexing at 1 as well.

**Comment by Pczek** [comment]
@kyokosdream Which specific released version did you use to modify with your code?
You can see all the changes we've made to the most recent version in this PR:
https://github.com/chiru-labs/ERC721A/pull/66/files#diff-833552e5bd4a4be3ada89b7874eedc6762fb91ed0890dda22e82a1936e6d60d8R339-R342

One thing which comes to mind, which could cause problems is the internally used `_exists()` function. Haven't tracked it completely where it could lead to some problems. It might be worth exploring in your modified contract. 🤔

**Comment by kyokosdream** [comment]
I'm going to integrate the latest changes to the repo (re-entrant safe mint and start at index 1) regardless of whether it's merged or not since we need to put this into production ASAP. I'll post a link to our contract implementation on the Projects page.

**Comment by Vectorized** [comment]
@kyokosdream Open a PR for `projects.md`.

**Comment by cygaar** [comment]
This has now been addressed in #66
