### ISSUE TITLE
ERC721A Contracts Classified as ERC-20 Tokens in Etherscan

### ISSUE THREAD

**Issue by 0xfcks** [chiru-labs/ERC721A#454]
I've been struggling to understand why Etherscan is not displaying the proper Token Holders data for a [ERC721A contract](https://etherscan.io/address/0x5cf51e611b36e9b3bf4e5b36da908fa3b040961e#code) inside its [Token Page](https://info.etherscan.com/understanding-token-page/).

I finally recognized that Etherscan was classifying my `ERC721A` contract as an `ERC-20` token. After reading this [StackOverflow thread](https://ethereum.stackexchange.com/questions/78678/smart-contract-overview-erc-20-instead-of-erc-721/78685#78685) that seemed to suggest that my `ERC721A` contract does not implement the full `EIP-721` interface. 

When I checked the `ERC721A` contract against the `EIP-721` interface it seems all the same functions exist but the arguments contained in `ERC721A` are expressed slightly different from the `EIP-721` (`ERC721A` uses underscores `_`). For example, 

`EIP-721` `balanceOf` function signature:
``` function balanceOf(address _owner)```
vs
`ERC721A` `balanceOf` event signature:
```function balanceOf(address owner)```

The function signatures, however, are still the same `0x70a08231`.

Just wondering if any one else has had issues with this in the past.

**Comment by Vectorized** [comment]
[See here ](https://chiru-labs.github.io/ERC721A/#/migration?id=supportsinterface)

**Comment by 0xfcks** [comment]
gotcha! thanks!
