### ISSUE TITLE
What is the purpose of this function on L911?

### ISSUE THREAD

**Issue by Lruquaf** [chiru-labs/ERC721A#477]
Is this a redundant function? When it is implemented, is there a security issue?

```
/**
 * @dev Equivalent to `_approve(to, tokenId, false)`.
*/
    function _approve(address to, uint256 tokenId) internal virtual {
        _approve(to, tokenId, false);
    }
```

When we enter the core `_approve` function with false as `approvalCheck`, it's so dangerous. Why is there so implementation in contract?

**Comment by Vectorized** [comment]
Note that this function is internal. 

It is for devs who may want to do their on custom checks instead of using the default check.

**Comment by Lruquaf** [comment]
Thanks, i'll close it.
