### ISSUE TITLE
seedAllowlist

### ISSUE THREAD

**Issue by enri90** [chiru-labs/ERC721A#52]
Truffle through unit test try catch error this message appears to me does it affect the smart contract?

Invalid number of parameters for "allowlist". Got 0 expected 1!

`
function seedAllowlist(address[] memory addresses, uint256[] memory numSlots) external onlyOwner{
    require( addresses.length == numSlots.length, "addresses does not match numSlots length");
    for (uint256 i = 0; i < addresses.length; i++) {
      allowlist[addresses[i]] = numSlots[i];
    }
  }
`

**Comment by ottogutierrez** [comment]
Is the allowlist a feature you're implementing, or is it a built-in feature?
