### ISSUE TITLE
_setOwnersExplicit is not used

### ISSUE THREAD

**Issue by MrMcGoats** [chiru-labs/ERC721A#7]
`_setOwnersExplicit` has internal visibility, but is never called. I understand this could still be useful for implementations extending ERC721A, however, the current contract can be used as-is and this function is effectively just wasting gas in its current state.

I think it would make sense to either remove it entirely or add it as an optional extension. Or even possibly add an external function that does nothing other than call `_setOwnersExplicit`.

**Comment by cygaar** [comment]
We are going to be adding this as an optional extension

**Comment by NeoDigi** [comment]
This can probably be close be #34

**Comment by cygaar** [comment]
Cool, moved to an extension as part of #34
